package com.citacloud.app.services;
import com.citacloud.app.models.AuditoriaEvento; import com.citacloud.app.repositories.AuditoriaEventoRepository; import com.citacloud.app.security.*; import jakarta.servlet.http.HttpServletRequest; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class AuditoriaService {
 public record Cambio(String campo,String anterior,String nuevo){} public record Resumen(long eventosHoy,long usuarios,long cambios,long accesosSensibles){} public record Pagina(List<AuditoriaEvento> eventos,long total){} private static final Set<String> PROTEGIDOS=Set.of("password","password_hash","access_token","refresh_token","api_key","secret","otp","notas","observaciones"); private final AuditoriaEventoRepository repo; private final HttpServletRequest request; public AuditoriaService(AuditoriaEventoRepository repo,HttpServletRequest request){this.repo=repo;this.request=request;}
 @Transactional public void registrar(UUID empresa,UUID usuario,String modulo,String accion,String entidad,UUID registro,String recurso){registrar(empresa,usuario,modulo,accion,entidad,registro,recurso,null,List.of(),"SUCCESS",null,false);}
 @Transactional public void registrar(UUID empresa,UUID usuario,String modulo,String accion,String entidad,UUID registro,String recurso,UUID paciente,List<Cambio> cambios,String resultado,String motivo,boolean sensible){if(empresa==null)return; AuditoriaEvento e=new AuditoriaEvento();e.setEmpresaId(empresa);e.setUsuarioId(usuario!=null?usuario:usuarioActual());e.setModulo(modulo);e.setAccion(accion);e.setEntidad(entidad);e.setRegistroId(registro);e.setRecurso(limitar(recurso,255));e.setPacienteId(paciente);e.setRolUsuario(rolActual());e.setIp(ip());e.setDispositivo(limitar(request==null?null:request.getHeader("User-Agent"),255));e.setDatosAnteriores(cambios(cambios,true));e.setDatosNuevos(cambios(cambios,false));e.setResultado(resultado==null?"SUCCESS":resultado);e.setMotivo(limitar(motivo,3000));e.setSensible(sensible);repo.save(e);}
 @Transactional(readOnly=true) public List<AuditoriaEvento> listar(UUID empresa,LocalDate desde,LocalDate hasta,UUID usuario,String modulo,String accion,String resultado,String texto){if(empresa==null)return List.of();LocalDateTime ini=(desde==null?LocalDate.of(2000,1,1):desde).atStartOfDay(), fin=(hasta==null?LocalDate.now():hasta).atTime(LocalTime.MAX);String b=n(texto);return repo.findByEmpresaIdAndFechaBetweenOrderByFechaDesc(empresa,ini,fin).stream().filter(e->usuario==null||usuario.equals(e.getUsuarioId())).filter(e->v(modulo)||modulo.equals(e.getModulo())).filter(e->v(accion)||accion.equals(e.getAccion())).filter(e->v(resultado)||resultado.equals(e.getResultado())).filter(e->b.isBlank()||n(e.getModulo()).contains(b)||n(e.getAccion()).contains(b)||n(e.getRecurso()).contains(b)||n(e.getEntidad()).contains(b)).toList();}
 @Transactional(readOnly=true) public Pagina buscarPagina(UUID empresa,LocalDate desde,LocalDate hasta,UUID usuario,String modulo,String resultado,String texto,int pagina,int tamanio){if(empresa==null)return new Pagina(List.of(),0);LocalDateTime ini=(desde==null?LocalDate.of(2000,1,1):desde).atStartOfDay(),fin=(hasta==null?LocalDate.now():hasta).atTime(LocalTime.MAX);Page<AuditoriaEvento> resultadoPagina=repo.buscar(empresa,ini,fin,usuario,v(modulo)?null:modulo,v(resultado)?null:resultado,texto==null?"":texto.trim(),PageRequest.of(Math.max(0,pagina),Math.max(1,tamanio)));return new Pagina(resultadoPagina.getContent(),resultadoPagina.getTotalElements());}
 @Transactional(readOnly=true) public AuditoriaEvento obtener(UUID empresa,UUID id){return repo.findByIdAndEmpresaId(id,empresa).orElseThrow(()->new IllegalArgumentException("Evento no encontrado para esta empresa."));}
 @Transactional(readOnly=true) public Resumen resumen(UUID e,LocalDate d,LocalDate h){List<AuditoriaEvento>x=listar(e,d,h,null,null,null,null,null);return new Resumen(x.stream().filter(a->a.getFecha().toLocalDate().equals(LocalDate.now())).count(),x.stream().map(AuditoriaEvento::getUsuarioId).filter(Objects::nonNull).distinct().count(),x.stream().filter(a->a.getAccion().contains("CREATED")||a.getAccion().contains("UPDATED")||a.getAccion().contains("ARCHIVED")||a.getAccion().contains("CANCELLED")||a.getAccion().contains("RESCHEDULED")).count(),x.stream().filter(AuditoriaEvento::isSensible).count());}
 private String cambios(List<Cambio>x,boolean anterior){if(x==null||x.isEmpty())return null;return x.stream().map(c->amigable(c.campo())+": "+proteger(c.campo(),anterior?c.anterior():c.nuevo())).reduce((a,b)->a+"\n"+b).orElse(null);} private String proteger(String c,String x){return x==null?"—":PROTEGIDOS.contains(n(c))?"[PROTEGIDO]":limitar(x,1000);} private String amigable(String c){return Map.of("telefono","Teléfono","email","Correo electrónico","documento","Documento","estado","Estado","fecha","Fecha","horaInicio","Hora de inicio","horaFin","Hora de fin","motivo","Motivo","nombre","Nombre","apellido","Apellido").getOrDefault(c,c);} private UUID usuarioActual(){TenantUserDetails u=AuthService.getAuthenticatedUser();return u==null?null:u.getUsuarioId();} private String rolActual(){TenantUserDetails u=AuthService.getAuthenticatedUser();return u==null?null:u.getAuthorities().stream().map(a->a.getAuthority()).filter(a->a.startsWith("ROLE_")).findFirst().map(a->a.substring(5)).orElse(null);} private String ip(){if(request==null)return null;String x=request.getHeader("X-Forwarded-For");return limitar(x==null?request.getRemoteAddr():x.split(",")[0].trim(),64);} private String n(String x){return x==null?"":x.toLowerCase(Locale.ROOT);} private boolean v(String x){return x==null||x.isBlank();} private String limitar(String x,int m){return x==null?null:x.length()<=m?x:x.substring(0,m);}
}
