package com.citacloud.app.services;

import com.citacloud.app.models.*;
import com.citacloud.app.repositories.*;
import com.citacloud.app.security.*;
import jakarta.persistence.EntityManager;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.LocalDateTime; import java.util.*;

@Service public class CajaService {
 public record Resumen(SesionCaja sesion,BigDecimal ingresos,BigDecimal egresos,BigDecimal efectivoEsperado,Map<String,BigDecimal> porMetodo,BigDecimal totalCobrado,List<MovimientoCaja> movimientos){}
 @Transactional(readOnly=true) public List<Caja> cajas(UUID empresa){requiere("CASH_REGISTER_VIEW");return cajas.findByEmpresaIdOrderByNombre(empresa);}
@Transactional(readOnly=true) public List<Caja> autorizadas(UUID empresa,UUID sucursal){TenantUserDetails u=actualRequerido(empresa);return u.getAuthorities().stream().anyMatch(a->a.getAuthority().equals("ROLE_ADMINISTRADOR")||a.getAuthority().equals("ROLE_SUPERADMIN"))?cajas.findByEmpresaIdAndSucursalIdAndActivaTrueOrderByNombre(empresa,sucursal):cajas.autorizadas(empresa,sucursal,u.getUsuarioId());}
@Transactional public Caja crearCaja(UUID empresa,UUID sucursalId,String codigo,String nombre,String descripcion){requiere("CASH_REGISTER_CREATE");Sucursal s=sucursales.findByIdAndEmpresaId(sucursalId,empresa).orElseThrow();if(nombre==null||nombre.isBlank())throw new IllegalArgumentException("El nombre es obligatorio.");codigo=codigo==null||codigo.isBlank()?siguiente(empresa,"siguiente_caja","CAJ-"):codigo.trim().toUpperCase(Locale.ROOT);if(cajas.existsByEmpresaIdAndCodigoIgnoreCase(empresa,codigo.trim()))throw new IllegalArgumentException("Ya existe una caja con ese código.");Caja c=new Caja();c.setEmpresaId(empresa);c.setSucursal(s);c.setCodigo(codigo.trim().toUpperCase(Locale.ROOT));c.setNombre(nombre.trim());c.setDescripcion(descripcion);usuarios.findByIdAndEmpresaId(actualRequerido(empresa).getUsuarioId(),empresa).ifPresent(c.getUsuarios()::add);Caja guardada=cajas.save(c);auditoria.registrar(empresa,actualRequerido(empresa).getUsuarioId(),"CAJA","CASH_REGISTER_CREATED","CAJA",guardada.getId(),guardada.getCodigo(),null,List.of(),"SUCCESS",null,true);return guardada;}
 @Transactional public Caja editarCaja(UUID empresa,UUID cajaId,UUID sucursalId,String codigo,String nombre,String descripcion){requiere("CASH_REGISTER_EDIT");Caja c=cajas.findByIdAndEmpresaId(cajaId,empresa).orElseThrow();Sucursal s=sucursales.findByIdAndEmpresaId(sucursalId,empresa).orElseThrow();c.setSucursal(s);c.setCodigo(codigo.trim().toUpperCase(Locale.ROOT));c.setNombre(nombre.trim());c.setDescripcion(descripcion);return cajas.save(c);}
 @Transactional public Caja asignarUsuarios(UUID empresa,UUID cajaId,Collection<UUID> ids){requiere("CASH_REGISTER_ASSIGN");Caja c=cajas.findByIdAndEmpresaId(cajaId,empresa).orElseThrow();c.getUsuarios().clear();if(ids!=null)ids.stream().map(id->usuarios.findByIdAndEmpresaId(id,empresa).orElseThrow()).forEach(c.getUsuarios()::add);return cajas.save(c);}
 @Transactional public void asignarCajasUsuario(UUID empresa,UUID usuarioId,Collection<UUID> ids){requiere("CASH_REGISTER_ASSIGN");Usuario u=usuarios.findByIdAndEmpresaId(usuarioId,empresa).orElseThrow();Set<UUID> seleccionadas=ids==null?Set.of():new HashSet<>(ids);for(Caja c:cajas.findByEmpresaIdOrderByNombre(empresa)){if(seleccionadas.contains(c.getId()))c.getUsuarios().add(u);else c.getUsuarios().removeIf(x->usuarioId.equals(x.getId()));cajas.save(c);}}
 @Transactional public Caja activar(UUID empresa,UUID cajaId,boolean activa){requiere("CASH_REGISTER_TOGGLE");Caja c=cajas.findByIdAndEmpresaId(cajaId,empresa).orElseThrow();c.setActiva(activa);return cajas.save(c);}
 private final SesionCajaRepository sesiones; private final MovimientoCajaRepository movimientos; private final SucursalRepository sucursales; private final CajaRepository cajas; private final UsuarioRepository usuarios; private final EntityManager em; private final AuditoriaService auditoria; private final NotificacionService notificaciones; private final JasperPdfService jasper; private final EmpresaRepository empresas;
 public CajaService(SesionCajaRepository sesiones,MovimientoCajaRepository movimientos,SucursalRepository sucursales,CajaRepository cajas,UsuarioRepository usuarios,EntityManager em,AuditoriaService auditoria,NotificacionService notificaciones,JasperPdfService jasper,EmpresaRepository empresas){this.sesiones=sesiones;this.movimientos=movimientos;this.sucursales=sucursales;this.cajas=cajas;this.usuarios=usuarios;this.em=em;this.auditoria=auditoria;this.notificaciones=notificaciones;this.jasper=jasper;this.empresas=empresas;}
 @Transactional(readOnly=true) public Optional<SesionCaja> actual(UUID empresa,UUID sucursal){TenantUserDetails u=actual();return u==null||sucursal==null?Optional.empty():sesiones.findByEmpresaIdAndSucursalIdAndAbiertoPorAndEstado(empresa,sucursal,u.getUsuarioId(),"OPEN");}
@Transactional(readOnly=true) public List<SesionCaja> historial(UUID empresa){return empresa==null?List.of():sesiones.findByEmpresaIdOrderByAbiertoEnDesc(empresa).stream().limit(25).toList();}
 @Transactional(readOnly=true) public List<SesionCaja> historial(UUID empresa,String texto,UUID sucursalId,UUID responsable,String estado,Boolean conDiferencia){String q=texto==null?"":texto.trim().toLowerCase(Locale.ROOT);return historial(empresa).stream().filter(s->sucursalId==null||s.getSucursal().getId().equals(sucursalId)).filter(s->responsable==null||responsable.equals(s.getAbiertoPor())).filter(s->estado==null||estado.isBlank()||estado.equalsIgnoreCase(s.getEstado())).filter(s->!Boolean.TRUE.equals(conDiferencia)||s.getDiferencia()!=null&&s.getDiferencia().signum()!=0).filter(s->q.isBlank()||s.getNumero().toLowerCase(Locale.ROOT).contains(q)).toList();}
 @Transactional(readOnly=true) public Resumen resumen(UUID empresa,UUID sesionId){SesionCaja s=sesion(empresa,sesionId);List<MovimientoCaja> lista=movimientos.findByEmpresaIdAndSesionIdOrderByCreadoEnAsc(empresa,sesionId);return resumen(s,lista);}
 @Transactional(readOnly=true) public byte[] generarCierre(UUID empresa,UUID sesionId){SesionCaja s=sesion(empresa,sesionId);if(!"CLOSED".equals(s.getEstado()))throw new IllegalArgumentException("La sesión debe estar cerrada para generar el cierre.");Resumen r=resumen(empresa,sesionId);Map<String,Object> p=new HashMap<>();Empresa e=empresas.findById(empresa).orElseThrow();p.put("CLINICA",e.getNombre());p.put("RNC",e.getRncIdentificacion()==null?"":e.getRncIdentificacion());p.put("SUCURSAL",s.getSucursal().getNombre());p.put("DIRECCION",s.getSucursal().getDireccion()==null?"":s.getSucursal().getDireccion());p.put("CAJA",s.getCaja()==null?s.getNumero():s.getCaja().getNombre());p.put("USUARIO",usuarioNombre(empresa,s.getCerradoPor()!=null?s.getCerradoPor():s.getAbiertoPor()));p.put("NUMERO",s.getNumeroCierre()==null?s.getNumero():s.getNumeroCierre());p.put("APERTURA",fechaHora(s.getAbiertoEn()));p.put("CIERRE",fechaHora(s.getCerradoEn()));p.put("FONDO",s.getFondoInicial());p.put("INGRESOS",r.ingresos());p.put("EGRESOS",r.egresos());p.put("ESPERADO",s.getEfectivoEsperado());p.put("CONTADO",s.getEfectivoContado());p.put("DIFERENCIA",s.getDiferencia());p.put("MOTIVO",s.getMotivoDiferencia()==null?"":s.getMotivoDiferencia());p.put("DESGLOSE",r.porMetodo().isEmpty()?"Sin cobros registrados.":r.porMetodo().entrySet().stream().map(x->x.getKey()+": RD$ "+x.getValue().setScale(2)).collect(java.util.stream.Collectors.joining("\n")));List<Map<String,Object>> filas=r.movimientos().stream().map(m->{Map<String,Object>x=new HashMap<>();x.put("hora",fechaHora(m.getCreadoEn()));x.put("tipo",m.getTipo());x.put("referencia",m.getReferencia()==null?m.getNumero():m.getReferencia());x.put("metodo",m.getMetodoPago());x.put("entrada","IN".equals(m.getDireccion())?m.getMonto():BigDecimal.ZERO);x.put("salida","OUT".equals(m.getDireccion())?m.getMonto():BigDecimal.ZERO);return x;}).toList();return jasper.generar("cierre-caja",p,filas);}

 private String fechaHora(java.time.LocalDateTime value){return value==null?"":value.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy · h:mm a",java.util.Locale.US));}
 private String usuarioNombre(UUID id){if(id==null)return "";return usuarios.findById(id).map(u->u.getNombreCompleto()==null?u.getUsuario():u.getNombreCompleto()).orElse("");}
 private String usuarioNombre(UUID empresa,UUID id){if(id==null)return "";return usuarios.findByIdAndEmpresaId(id,empresa).map(u->u.getNombreCompleto()==null?u.getUsuario():u.getNombreCompleto()).orElse("");}
 @Transactional public SesionCaja abrir(UUID empresa,UUID sucursalId,BigDecimal fondo,String nota,String clave){requiere("CASH_OPEN");TenantUserDetails u=actualRequerido(empresa);if(clave!=null&&!clave.isBlank()){Optional<SesionCaja> previa=sesiones.findByEmpresaIdAndSucursalIdAndAbiertoPorAndEstado(empresa,sucursalId,u.getUsuarioId(),"OPEN");if(previa.isPresent())return previa.get();}Caja caja=cajas.autorizadas(empresa,sucursalId,u.getUsuarioId()).stream().findFirst().orElseThrow(()->new IllegalArgumentException("No tiene una caja activa asignada en esta sucursal."));Sucursal sucursal=sucursales.findByIdAndEmpresaId(sucursalId,empresa).orElseThrow(()->new IllegalArgumentException("Sucursal no encontrada para esta empresa."));if(!Boolean.TRUE.equals(sucursal.getActiva()))throw new IllegalArgumentException("La sucursal está inactiva.");if(sesiones.findByEmpresaIdAndSucursalIdAndAbiertoPorAndEstado(empresa,sucursalId,u.getUsuarioId(),"OPEN").isPresent())throw new IllegalArgumentException("Ya tienes una caja abierta en esta sucursal.");SesionCaja s=new SesionCaja();s.setEmpresaId(empresa);s.setSucursal(sucursal);s.setCaja(caja);s.setNumero(siguiente(empresa,"siguiente_caja","CJ-"));s.setAbiertoPor(u.getUsuarioId());s.setFondoInicial(dinero(fondo));s.setNotaApertura(limitar(nota,3000));s=sesiones.save(s);auditoria.registrar(empresa,u.getUsuarioId(),"CAJA","CASH_SESSION_OPENED","SESION_CAJA",s.getId(),s.getNumero(),null,List.of(new AuditoriaService.Cambio("fondoInicial",null,s.getFondoInicial().toPlainString())),"SUCCESS",null,true);return s;}
@Transactional public SesionCaja abrirEnCaja(UUID empresa,UUID sucursalId,UUID cajaId,BigDecimal fondo,String nota,String clave){requiere("CASH_OPEN");TenantUserDetails u=actualRequerido(empresa);Caja caja=autorizadas(empresa,sucursalId).stream().filter(c->c.getId().equals(cajaId)).findFirst().orElseThrow(()->new IllegalArgumentException("La caja no está asignada o no está activa para este usuario."));if(sesiones.findByEmpresaIdAndCajaIdAndEstado(empresa,cajaId,"OPEN").isPresent())throw new IllegalArgumentException("La caja seleccionada ya tiene un turno abierto.");Sucursal sucursal=sucursales.findByIdAndEmpresaId(sucursalId,empresa).orElseThrow(()->new IllegalArgumentException("Sucursal no encontrada para esta empresa."));SesionCaja s=new SesionCaja();s.setEmpresaId(empresa);s.setSucursal(sucursal);s.setCaja(caja);s.setNumero(siguiente(empresa,"siguiente_caja","CJ-"));s.setAbiertoPor(u.getUsuarioId());s.setFondoInicial(dinero(fondo));s.setNotaApertura(limitar(nota,3000));s=sesiones.save(s);auditoria.registrar(empresa,u.getUsuarioId(),"CAJA","CASH_SESSION_OPENED","SESION_CAJA",s.getId(),s.getNumero(),null,List.of(new AuditoriaService.Cambio("caja",null,caja.getCodigo())),"SUCCESS",null,true);return s;}
 @Transactional public MovimientoCaja ingreso(UUID empresa,UUID sesionId,BigDecimal monto,String metodo,String concepto,String nota,String clave){return manual(empresa,sesionId,monto,metodo,concepto,nota,"MANUAL_INCOME","IN","CASH_CREATE_INCOME",clave);}
 @Transactional public MovimientoCaja egreso(UUID empresa,UUID sesionId,BigDecimal monto,String metodo,String concepto,String nota,String clave){return manual(empresa,sesionId,monto,metodo,concepto,nota,"MANUAL_EXPENSE","OUT","CASH_CREATE_EXPENSE",clave);}
 @Transactional public SesionCaja cerrar(UUID empresa,UUID sesionId,BigDecimal contado,String nota,String motivo){requiere("CASH_CLOSE");SesionCaja s=sesion(empresa,sesionId);if(!"OPEN".equals(s.getEstado()))throw new IllegalArgumentException("La caja ya está cerrada.");Resumen r=resumen(s,movimientos.findByEmpresaIdAndSesionIdOrderByCreadoEnAsc(empresa,sesionId));BigDecimal esperado=r.efectivoEsperado(), efectivoContado=dinero(contado), diferencia=efectivoContado.subtract(esperado);if(diferencia.signum()!=0){requiere("CASH_CLOSE_WITH_DIFFERENCE");if(motivo==null||motivo.isBlank())throw new IllegalArgumentException("Indique la justificación de la diferencia.");}TenantUserDetails u=actualRequerido(empresa);s.setEfectivoEsperado(esperado);s.setEfectivoContado(efectivoContado);s.setDiferencia(diferencia);s.setNotaCierre(limitar(nota,3000));s.setMotivoDiferencia(limitar(motivo,3000));s.setCerradoPor(u.getUsuarioId());s.setCerradoEn(LocalDateTime.now());s.setEstado("CLOSED");sesiones.save(s);auditoria.registrar(empresa,u.getUsuarioId(),"CAJA",diferencia.signum()==0?"CASH_SESSION_CLOSED":"CASH_DIFFERENCE_DETECTED","SESION_CAJA",s.getId(),s.getNumero(),null,List.of(new AuditoriaService.Cambio("diferencia",null,diferencia.toPlainString())),"SUCCESS",motivo,true);if(diferencia.signum()!=0)notificaciones.crearEmpresa(empresa,"CASH_DIFFERENCE_DETECTED","CAJA","Diferencia en cierre de caja",s.getNumero()+" cerró con una diferencia de RD$ "+diferencia.setScale(2,RoundingMode.HALF_UP)+".","CASH_SESSION",s.getId());return s;}
 @Transactional public SesionCaja cerrarIdempotente(UUID empresa,UUID sesionId,BigDecimal contado,String nota,String motivo,String clave){requiere("CASH_CLOSE");String k=limitar(clave,100);if(k!=null&&!k.isBlank()){Optional<SesionCaja> previo=sesiones.findByEmpresaIdAndClaveCierre(empresa,k);if(previo.isPresent())return previo.get();}SesionCaja s=cerrar(empresa,sesionId,contado,nota,motivo);s.setClaveCierre(k);return sesiones.save(s);}
 @Transactional public void registrarPago(Pago pago){if(pago==null||pago.getSucursal()==null)return;SesionCaja s=sesiones.findByEmpresaIdAndSucursalIdAndAbiertoPorAndEstado(pago.getEmpresaId(),pago.getSucursal().getId(),pago.getUsuarioId(),"OPEN").orElseThrow(()->new IllegalArgumentException("Debe abrir una caja en la sucursal seleccionada antes de registrar un pago."));if(movimientos.findByPagoId(pago.getId()).isPresent())return;crear(s,"PAYMENT","IN",pago.getMetodoPago(),pago.getMonto(),"Pago "+pago.getNumero(),pago.getNumero(),pago.getObservacion(),pago,null);}
 @Transactional public void validarPagoEfectivo(UUID empresa,UUID sucursalId){TenantUserDetails u=actualRequerido(empresa);if(sucursalId==null)throw new IllegalArgumentException("Seleccione una sucursal para el pago en efectivo.");if(sesiones.findByEmpresaIdAndSucursalIdAndAbiertoPorAndEstado(empresa,sucursalId,u.getUsuarioId(),"OPEN").isEmpty())throw new IllegalArgumentException("Debe abrir una caja en la sucursal seleccionada antes de cobrar en efectivo.");}
 @Transactional public void registrarReembolso(ReembolsoPago reembolso){if(reembolso==null||reembolso.getPago()==null||reembolso.getPago().getSucursal()==null)return;TenantUserDetails u=actualRequerido(reembolso.getEmpresaId());SesionCaja s=sesiones.findByEmpresaIdAndSucursalIdAndAbiertoPorAndEstado(reembolso.getEmpresaId(),reembolso.getPago().getSucursal().getId(),u.getUsuarioId(),"OPEN").orElseThrow(()->new IllegalArgumentException("Debe tener una caja abierta para realizar el reembolso."));if(movimientos.findByReembolsoId(reembolso.getId()).isPresent())return;crear(s,"REFUND","OUT",reembolso.getMetodoPago(),reembolso.getMonto(),"Reembolso "+reembolso.getPago().getNumero(),reembolso.getPago().getNumero(),reembolso.getMotivo(),null,reembolso);}
 @Transactional public void reversar(UUID empresa,UUID movimientoId,String motivo){requiere("CASH_REVERSE_MOVEMENT");MovimientoCaja m=movimientos.findByIdAndEmpresaId(movimientoId,empresa).orElseThrow(()->new IllegalArgumentException("Movimiento no encontrado."));if(!"ACTIVE".equals(m.getEstado()))throw new IllegalArgumentException("El movimiento ya fue reversado.");if(!Set.of("MANUAL_INCOME","MANUAL_EXPENSE").contains(m.getTipo()))throw new IllegalArgumentException("Solo se pueden reversar movimientos manuales.");if(motivo==null||motivo.isBlank())throw new IllegalArgumentException("Indique el motivo de la reversión.");m.revertir(actualRequerido(empresa).getUsuarioId(),limitar(motivo,3000));movimientos.save(m);auditoria.registrar(empresa,null,"CAJA","CASH_MOVEMENT_REVERSED","MOVIMIENTO_CAJA",m.getId(),m.getNumero(),null,List.of(),"SUCCESS",motivo,true);}
 private MovimientoCaja manual(UUID e,UUID sid,BigDecimal monto,String metodo,String concepto,String nota,String tipo,String dir,String permiso,String clave){requiere(permiso);if(clave!=null&&!clave.isBlank()){Optional<MovimientoCaja> previo=movimientos.findByEmpresaIdAndClaveIdempotencia(e,limitar(clave,100));if(previo.isPresent())return previo.get();}SesionCaja s=sesion(e,sid);if(!"OPEN".equals(s.getEstado()))throw new IllegalArgumentException("No se pueden registrar movimientos en una caja cerrada.");if(concepto==null||concepto.isBlank())throw new IllegalArgumentException("Indique el concepto.");MovimientoCaja m=crear(s,tipo,dir,metodo,dinero(monto),concepto,null,nota,null,null);m.setClaveIdempotencia(limitar(clave,100));m=movimientos.save(m);auditoria.registrar(e,null,"CAJA",dir.equals("IN")?"CASH_INCOME_CREATED":"CASH_EXPENSE_CREATED","MOVIMIENTO_CAJA",m.getId(),m.getNumero(),null,List.of(new AuditoriaService.Cambio("monto",null,m.getMonto().toPlainString())),"SUCCESS",null,true);return m;}
 private MovimientoCaja crear(SesionCaja s,String tipo,String direccion,String metodo,BigDecimal monto,String concepto,String referencia,String nota,Pago pago,ReembolsoPago reembolso){if(monto.signum()<=0)throw new IllegalArgumentException("El monto debe ser mayor que cero.");MovimientoCaja m=new MovimientoCaja();m.setEmpresaId(s.getEmpresaId());m.setSucursal(s.getSucursal());m.setCaja(s.getCaja());m.setSesion(s);m.setNumero(siguiente(s.getEmpresaId(),"siguiente_movimiento_caja","MOV-"));m.setTipo(tipo);m.setDireccion(direccion);m.setMetodoPago(normalizarMetodo(metodo));m.setMonto(dinero(monto));m.setConcepto(limitar(concepto,255));m.setReferencia(limitar(referencia,120));m.setNotas(limitar(nota,3000));m.setPago(pago);m.setReembolso(reembolso);m.setCreadoPor(actualRequerido(s.getEmpresaId()).getUsuarioId());return movimientos.save(m);}
 private Resumen resumen(SesionCaja s,List<MovimientoCaja> lista){BigDecimal ingresos=BigDecimal.ZERO,egresos=BigDecimal.ZERO,efectivo=s.getFondoInicial();Map<String,BigDecimal> metodos=new LinkedHashMap<>();for(MovimientoCaja m:lista){if(!"ACTIVE".equals(m.getEstado()))continue;boolean entrada="IN".equals(m.getDireccion());if(entrada)ingresos=ingresos.add(m.getMonto());else egresos=egresos.add(m.getMonto());if("EFECTIVO".equals(m.getMetodoPago()))efectivo=entrada?efectivo.add(m.getMonto()):efectivo.subtract(m.getMonto());if("PAYMENT".equals(m.getTipo())&&entrada)metodos.merge(m.getMetodoPago(),m.getMonto(),BigDecimal::add);}BigDecimal total=metodos.values().stream().reduce(BigDecimal.ZERO,BigDecimal::add);return new Resumen(s,ingresos,egresos,dinero(efectivo),metodos,dinero(total),lista);}
 private SesionCaja sesion(UUID e,UUID id){return sesiones.findByIdAndEmpresaId(id,e).orElseThrow(()->new IllegalArgumentException("Sesión de caja no encontrada."));} private TenantUserDetails actual(){return AuthService.getAuthenticatedUser();} private TenantUserDetails actualRequerido(UUID e){TenantUserDetails u=actual();if(u==null||!e.equals(u.getEmpresaId()))throw new IllegalArgumentException("No existe una empresa autenticada.");return u;} private void requiere(String p){TenantUserDetails u=actual();if(u==null)throw new IllegalArgumentException("Debe iniciar sesión.");boolean admin=u.getAuthorities().stream().anyMatch(a->a.getAuthority().equals("ROLE_ADMINISTRADOR")||a.getAuthority().equals("ROLE_SUPERADMIN"));if(!admin&&u.getAuthorities().stream().noneMatch(a->a.getAuthority().equals(p)))throw new IllegalArgumentException("No tiene permiso para esta operación de caja.");} private String siguiente(UUID e,String campo,String prefijo){em.createNativeQuery("insert into consecutivos_financieros(empresa_id) values (?1) on conflict (empresa_id) do nothing").setParameter(1,e).executeUpdate();Number n=(Number)em.createNativeQuery("update consecutivos_financieros set "+campo+"="+campo+"+1 where empresa_id=?1 returning "+campo+"-1").setParameter(1,e).getSingleResult();return prefijo+"%06d".formatted(n.longValue());} private BigDecimal dinero(BigDecimal x){return (x==null?BigDecimal.ZERO:x).setScale(2,RoundingMode.HALF_UP);} private String normalizarMetodo(String x){String r=x==null?"EFECTIVO":x.trim().toUpperCase(Locale.ROOT);if(!Set.of("EFECTIVO","TARJETA","TRANSFERENCIA","CHEQUE","OTRO").contains(r))throw new IllegalArgumentException("Método de pago no válido.");return r;} private String limitar(String x,int max){return x==null?null:x.length()<=max?x:x.substring(0,max);}
}
