package com.citacloud.app.services;

import com.citacloud.app.models.*;
import com.citacloud.app.repositories.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.util.UUID;

@Service
public class ConsultaComplementariaService {
    private final PacienteRepository pacientes; private final AntecedenteMedicoRepository antecedentes;
    private final AlergiaPacienteRepository alergias; private final DiagnosticoRepository diagnosticos; private final TratamientoRepository tratamientos;
    public ConsultaComplementariaService(PacienteRepository pacientes, AntecedenteMedicoRepository antecedentes, AlergiaPacienteRepository alergias, DiagnosticoRepository diagnosticos, TratamientoRepository tratamientos) { this.pacientes=pacientes; this.antecedentes=antecedentes; this.alergias=alergias; this.diagnosticos=diagnosticos; this.tratamientos=tratamientos; }
    public java.util.List<AntecedenteMedico> listarAntecedentes(UUID empresa, UUID paciente) { return antecedentes.findByEmpresaIdAndPacienteId(empresa, paciente); }
    public java.util.List<AlergiaPaciente> listarAlergias(UUID empresa, UUID paciente) { return alergias.findByEmpresaIdAndPacienteId(empresa, paciente); }
    public java.util.List<Diagnostico> listarDiagnosticos(UUID empresa, UUID paciente) { return diagnosticos.findByEmpresaIdAndPacienteId(empresa, paciente); }
    public java.util.List<Tratamiento> listarTratamientos(UUID empresa, UUID paciente) { return tratamientos.findByEmpresaIdAndPacienteId(empresa, paciente); }
    @Transactional public void registrarAntecedente(UUID empresa, UUID paciente, UUID usuario, String tipo, String descripcion, LocalDate fecha, boolean fechaDesconocida, String estado, String relacion, String observaciones) { validarPaciente(empresa,paciente); obligatorio(tipo,"Tipo"); obligatorio(descripcion,"Descripción"); AntecedenteMedico x=new AntecedenteMedico(); x.setEmpresaId(empresa); x.setPacienteId(paciente); x.setRegistradoPor(usuario); x.setCreadoEn(java.time.LocalDateTime.now()); aplicarAntecedente(x,tipo,descripcion,fecha,fechaDesconocida,estado,relacion,observaciones); antecedentes.save(x); }
    @Transactional public void registrarAlergia(UUID empresa, UUID paciente, String alergeno, String tipo, String reaccion, String severidad) { validarPaciente(empresa,paciente); obligatorio(alergeno,"Alérgeno"); AlergiaPaciente x=new AlergiaPaciente(); x.setEmpresaId(empresa); x.setPacienteId(paciente); x.setAlergeno(alergeno); x.setTipo(tipo); x.setReaccion(reaccion); x.setSeveridad(severidad==null?"LEVE":severidad); alergias.save(x); }
    @Transactional public void registrarAlergiaCompleta(UUID empresa,UUID paciente,UUID usuario,String alergeno,String tipo,String reaccion,String severidad,String estado,LocalDate fecha,String observaciones){validarPaciente(empresa,paciente);obligatorio(alergeno,"Alérgeno");obligatorio(tipo,"Tipo");AlergiaPaciente x=new AlergiaPaciente();x.setEmpresaId(empresa);x.setPacienteId(paciente);x.setRegistradoPor(usuario);x.setCreadoEn(java.time.LocalDateTime.now());aplicarAlergia(x,alergeno,tipo,reaccion,severidad,estado,fecha,observaciones);alergias.save(x);}
    @Transactional public void registrarDiagnostico(UUID empresa, UUID paciente, String codigo, String descripcion, String tipo, String observaciones) { validarPaciente(empresa,paciente); obligatorio(descripcion,"Descripción"); Diagnostico x=new Diagnostico(); x.setEmpresaId(empresa); x.setPacienteId(paciente); x.setCodigo(codigo); x.setDescripcion(descripcion); x.setTipo(tipo); x.setObservaciones(observaciones); diagnosticos.save(x); }
    @Transactional public void registrarDiagnosticoCompleto(UUID empresa,UUID paciente,UUID usuario,String codigo,String descripcion,String tipo,boolean principal,String estado,LocalDate fecha,String observaciones){validarPaciente(empresa,paciente);Diagnostico x=new Diagnostico();x.setEmpresaId(empresa);x.setPacienteId(paciente);x.setRegistradoPor(usuario);x.setCreadoEn(java.time.LocalDateTime.now());aplicarDiagnostico(x,empresa,paciente,codigo,descripcion,tipo,principal,estado,fecha,observaciones);diagnosticos.save(x);}
    @Transactional public void registrarTratamiento(UUID empresa, UUID paciente, String descripcion, LocalDate inicio, LocalDate fin, String indicaciones) { validarPaciente(empresa,paciente); obligatorio(descripcion,"Tratamiento"); if(inicio!=null&&fin!=null&&fin.isBefore(inicio)) throw new IllegalArgumentException("La fecha de finalización no puede ser anterior a la de inicio."); Tratamiento x=new Tratamiento(); x.setEmpresaId(empresa); x.setPacienteId(paciente); x.setDescripcion(descripcion); x.setFechaInicio(inicio); x.setFechaFin(fin); x.setIndicaciones(indicaciones); tratamientos.save(x); }
    @Transactional public void registrarTratamientoCompleto(UUID empresa, UUID paciente, UUID usuario, UUID diagnostico, String tipo, String descripcion, LocalDate inicio, LocalDate fin, String estado, String indicaciones, String observaciones) { validarPaciente(empresa,paciente); Tratamiento x=new Tratamiento(); x.setEmpresaId(empresa); x.setPacienteId(paciente); x.setRegistradoPor(usuario); x.setCreadoEn(java.time.LocalDateTime.now()); aplicarTratamiento(x,empresa,paciente,diagnostico,tipo,descripcion,inicio,fin,estado,indicaciones,observaciones); tratamientos.save(x); }
    @Transactional public void actualizarAntecedente(UUID empresa, UUID id, String tipo, String descripcion, LocalDate fecha, boolean fechaDesconocida, String estado, String relacion, String observaciones) { AntecedenteMedico x=antecedentes.findById(id).filter(v->empresa.equals(v.getEmpresaId())).orElseThrow(()->new IllegalArgumentException("Registro no encontrado para esta empresa.")); aplicarAntecedente(x,tipo,descripcion,fecha,fechaDesconocida,estado,relacion,observaciones); antecedentes.save(x); }
    @Transactional public void actualizarAlergia(UUID empresa, UUID id, String alergeno, String tipo, String reaccion, String severidad) { AlergiaPaciente x=alergias.findById(id).filter(v->empresa.equals(v.getEmpresaId())).orElseThrow(()->new IllegalArgumentException("Registro no encontrado para esta empresa.")); obligatorio(alergeno,"Alérgeno"); x.setAlergeno(alergeno); x.setTipo(tipo); x.setReaccion(reaccion); x.setSeveridad(severidad==null?"LEVE":severidad); alergias.save(x); }
    @Transactional public void actualizarAlergiaCompleta(UUID empresa,UUID id,String alergeno,String tipo,String reaccion,String severidad,String estado,LocalDate fecha,String observaciones){AlergiaPaciente x=alergias.findById(id).filter(v->empresa.equals(v.getEmpresaId())).orElseThrow(()->new IllegalArgumentException("Registro no encontrado para esta empresa."));aplicarAlergia(x,alergeno,tipo,reaccion,severidad,estado,fecha,observaciones);alergias.save(x);}
    @Transactional public void actualizarDiagnostico(UUID empresa, UUID id, String codigo, String descripcion, String tipo, String observaciones) { Diagnostico x=diagnosticos.findById(id).filter(v->empresa.equals(v.getEmpresaId())).orElseThrow(()->new IllegalArgumentException("Registro no encontrado para esta empresa.")); obligatorio(descripcion,"Descripción"); x.setCodigo(codigo); x.setDescripcion(descripcion); x.setTipo(tipo); x.setObservaciones(observaciones); diagnosticos.save(x); }
    @Transactional public void actualizarDiagnosticoCompleto(UUID empresa,UUID id,String codigo,String descripcion,String tipo,boolean principal,String estado,LocalDate fecha,String observaciones){Diagnostico x=diagnosticos.findById(id).filter(v->empresa.equals(v.getEmpresaId())).orElseThrow(()->new IllegalArgumentException("Registro no encontrado para esta empresa."));aplicarDiagnostico(x,empresa,x.getPacienteId(),codigo,descripcion,tipo,principal,estado,fecha,observaciones);diagnosticos.save(x);}
    @Transactional public void actualizarTratamiento(UUID empresa, UUID id, String descripcion, LocalDate inicio, LocalDate fin, String indicaciones) { Tratamiento x=tratamientos.findById(id).filter(v->empresa.equals(v.getEmpresaId())).orElseThrow(()->new IllegalArgumentException("Registro no encontrado para esta empresa.")); obligatorio(descripcion,"Tratamiento"); if(inicio!=null&&fin!=null&&fin.isBefore(inicio)) throw new IllegalArgumentException("La fecha de finalización no puede ser anterior a la de inicio."); x.setDescripcion(descripcion); x.setFechaInicio(inicio); x.setFechaFin(fin); x.setIndicaciones(indicaciones); tratamientos.save(x); }
    @Transactional public void actualizarTratamientoCompleto(UUID empresa, UUID id, UUID diagnostico, String tipo, String descripcion, LocalDate inicio, LocalDate fin, String estado, String indicaciones, String observaciones) { Tratamiento x=tratamientos.findById(id).filter(v->empresa.equals(v.getEmpresaId())).orElseThrow(()->new IllegalArgumentException("Registro no encontrado para esta empresa.")); aplicarTratamiento(x,empresa,x.getPacienteId(),diagnostico,tipo,descripcion,inicio,fin,estado,indicaciones,observaciones); tratamientos.save(x); }
    private void validarPaciente(UUID empresa, UUID paciente) { if(empresa==null||paciente==null||pacientes.findByIdAndEmpresaId(paciente,empresa).isEmpty()) throw new IllegalArgumentException("Paciente no encontrado para esta empresa."); }
    private void aplicarAntecedente(AntecedenteMedico x,String tipo,String descripcion,LocalDate fecha,boolean desconocida,String estado,String relacion,String observaciones){obligatorio(tipo,"Tipo"); obligatorio(descripcion,"Descripción"); x.setTipo(tipo);x.setDescripcion(descripcion);x.setFechaDesconocida(desconocida);x.setFechaAproximada(desconocida?null:fecha);x.setEstado(estado==null?"ACTIVO":estado);x.setRelacionFamiliar("FAMILIAR".equals(tipo)?relacion:null);x.setObservaciones(observaciones);x.setActualizadoEn(java.time.LocalDateTime.now());}
    private void aplicarAlergia(AlergiaPaciente x,String alergeno,String tipo,String reaccion,String severidad,String estado,LocalDate fecha,String observaciones){x.setAlergeno(alergeno);x.setTipo(tipo);x.setReaccion(reaccion);x.setSeveridad(severidad==null?"LEVE":severidad);x.setEstado(estado==null?"ACTIVA":estado);x.setFechaAproximada(fecha);x.setObservaciones(observaciones);x.setActualizadoEn(java.time.LocalDateTime.now());}
    private void aplicarDiagnostico(Diagnostico x,UUID empresa,UUID paciente,String codigo,String descripcion,String tipo,boolean principal,String estado,LocalDate fecha,String observaciones){obligatorio(descripcion,"Diagnóstico");if(principal)diagnosticos.findByEmpresaIdAndPacienteId(empresa,paciente).forEach(d->{if(!d.getId().equals(x.getId())){d.setPrincipal(false);diagnosticos.save(d);}});x.setCodigo(codigo);x.setDescripcion(descripcion);x.setTipo(tipo);x.setPrincipal(principal);x.setEstado(estado==null?"ACTIVO":estado);x.setFechaDiagnostico(fecha==null?LocalDate.now():fecha);x.setObservaciones(observaciones);x.setActualizadoEn(java.time.LocalDateTime.now());}
    private void aplicarTratamiento(Tratamiento x,UUID empresa,UUID paciente,UUID diagnostico,String tipo,String descripcion,LocalDate inicio,LocalDate fin,String estado,String indicaciones,String observaciones){obligatorio(tipo,"Tipo de tratamiento");obligatorio(descripcion,"Tratamiento");obligatorio(indicaciones,"Indicaciones");if(inicio==null)throw new IllegalArgumentException("La fecha de inicio es obligatoria.");if(fin!=null&&fin.isBefore(inicio))throw new IllegalArgumentException("La fecha de finalización no puede ser anterior a la de inicio.");if(diagnostico!=null&&diagnosticos.findById(diagnostico).filter(d->empresa.equals(d.getEmpresaId())&&paciente.equals(d.getPacienteId())).isEmpty())throw new IllegalArgumentException("El diagnóstico seleccionado no pertenece a este paciente.");x.setDiagnosticoId(diagnostico);x.setTipo(tipo);x.setDescripcion(descripcion);x.setFechaInicio(inicio);x.setFechaFin(fin);x.setEstado(estado==null?"ACTIVO":estado);x.setIndicaciones(indicaciones);x.setObservaciones(observaciones);x.setActualizadoEn(java.time.LocalDateTime.now());}
    private void obligatorio(String valor,String nombre) { if(valor==null||valor.isBlank()) throw new IllegalArgumentException(nombre+" es obligatorio."); }
}
