package com.citacloud.app.services;

import com.citacloud.app.security.AuthService;
import com.citacloud.app.security.TenantUserDetails;
import org.springframework.stereotype.Service;
import java.time.format.DateTimeFormatter;
import java.util.*;

@Service
public class ManagementControlPdfService {
    private final ManagementControlReportService reportes; private final JasperPdfService jasper; private final AuditoriaService auditoria;
    public ManagementControlPdfService(ManagementControlReportService reportes, JasperPdfService jasper, AuditoriaService auditoria) { this.reportes=reportes;this.jasper=jasper;this.auditoria=auditoria; }
    public byte[] generar(UUID empresaId, ManagementControlReportService.Filtros filtros, String clinica) {
        TenantUserDetails u=AuthService.getAuthenticatedUser(); if(u==null || !empresaId.equals(u.getEmpresaId()) || !puede(u,"reports.management.export.pdf")) throw new IllegalArgumentException("No tienes permiso para exportar este reporte.");
        var reporte=reportes.generar(empresaId,filtros); List<Map<String,Object>> filas=new ArrayList<>(); for(var p:reporte.productividad()) filas.add(Map.of("medico",p.medico(),"citas",p.citas(),"atendidos",p.atendidas(),"canceladas",p.canceladas(),"noShow",p.noShow(),"promedio",p.promedioDia())); if(filas.isEmpty()) filas.add(Map.of("medico","Sin información","citas",0L,"atendidos",0L,"canceladas",0L,"noShow",0L,"promedio",0d));
        DateTimeFormatter formatoFecha=DateTimeFormatter.ofPattern("dd/MM/yyyy"); Map<String,Object> parametros=new HashMap<>(); parametros.put("CLINICA",clinica==null?"CitaCloud":clinica); parametros.put("PERIODO",formatoFecha.format(filtros.desde())+" - "+formatoFecha.format(filtros.hasta())); parametros.put("TOTAL_CITAS",reporte.totalCitas()); parametros.put("ATENDIDOS",reporte.pacientesAtendidos()); parametros.put("NUEVOS",reporte.pacientesNuevos()); parametros.put("CANCELADAS",reporte.resumen().stream().filter(k->"Canceladas".equals(k.nombre())).findFirst().map(k->k.valor()).orElse("—")); parametros.put("NO_SHOW",reporte.resumen().stream().filter(k->"No-show".equals(k.nombre())).findFirst().map(k->k.valor()).orElse("—")); parametros.put("ASISTENCIA",reporte.resumen().stream().filter(k->"Asistencia".equals(k.nombre())).findFirst().map(k->k.valor()).orElse("—")); parametros.put("ESTADOS",reporte.estados().stream().map(x->x.estado()+": "+x.cantidad()+" ("+x.porcentaje()+"%)").collect(java.util.stream.Collectors.joining("  |  "))); parametros.put("ESPECIALIDADES",reporte.especialidades().isEmpty()?"Sin citas registradas para el período seleccionado.":reporte.especialidades().stream().map(x->"• "+x.especialidad()+"  —  "+x.citas()+" citas  |  "+x.atendidas()+" atendidas  |  "+x.porcentaje()+"%").collect(java.util.stream.Collectors.joining("\n"))); parametros.put("INDICADORES",reporte.indicadores().stream().map(x->"• "+x.indicador()+"  |  Resultado: "+x.resultado()+"  |  Meta: "+x.meta()+"  |  "+x.estado()).collect(java.util.stream.Collectors.joining("\n"))); parametros.put("ALERTAS",reporte.alertas().isEmpty()?"✓ Sin alertas críticas durante el período seleccionado.":String.join("\n",reporte.alertas())); parametros.put("GENERADO",java.time.LocalDateTime.now().toString());
        var especialidades=reporte.especialidades(); parametros.put("ESP_NOMBRES",especialidades.isEmpty()?"Sin registros":especialidades.stream().map(x->x.especialidad()).collect(java.util.stream.Collectors.joining("\n"))); parametros.put("ESP_CITAS",especialidades.isEmpty()?"—":especialidades.stream().map(x->String.valueOf(x.citas())).collect(java.util.stream.Collectors.joining("\n"))); parametros.put("ESP_ATENDIDOS",especialidades.isEmpty()?"—":especialidades.stream().map(x->String.valueOf(x.atendidas())).collect(java.util.stream.Collectors.joining("\n"))); parametros.put("ESP_PORCENTAJES",especialidades.isEmpty()?"—":especialidades.stream().map(x->x.porcentaje()+"%").collect(java.util.stream.Collectors.joining("\n"))); var indicadores=reporte.indicadores(); parametros.put("IND_NOMBRES",indicadores.stream().map(x->x.indicador()).collect(java.util.stream.Collectors.joining("\n"))); parametros.put("IND_RESULTADOS",indicadores.stream().map(x->x.resultado()).collect(java.util.stream.Collectors.joining("\n"))); parametros.put("IND_METAS",indicadores.stream().map(x->x.meta()).collect(java.util.stream.Collectors.joining("\n"))); parametros.put("IND_ESTADOS",indicadores.stream().map(x->x.estado()).collect(java.util.stream.Collectors.joining("\n")));
        byte[] pdf=jasper.generar("gestion_control",parametros,filas); auditoria.registrar(empresaId,u.getUsuarioId(),"REPORTES","REPORT_EXPORTED","MANAGEMENT_CONTROL",null,"Gestión y Control PDF",null,List.of(),"SUCCESS",filtros.desde()+" a "+filtros.hasta(),false); return pdf;
    }
    private boolean puede(TenantUserDetails u,String permiso){return u.getAuthorities().stream().anyMatch(a->permiso.equals(a.getAuthority())||"ROLE_ADMINISTRADOR".equals(a.getAuthority())||"ROLE_SUPERADMIN".equals(a.getAuthority()));}
}
