package com.citacloud.app.services;

import com.citacloud.app.models.*; import com.citacloud.app.repositories.*; import com.lowagie.text.Document; import com.lowagie.text.PageSize; import com.lowagie.text.Paragraph; import com.lowagie.text.FontFactory; import com.lowagie.text.pdf.PdfWriter; import com.lowagie.text.pdf.PdfPCell; import com.lowagie.text.pdf.PdfPTable; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.io.ByteArrayOutputStream; import java.time.*; import java.util.*;

@Service public class OrdenEstudioService {
 private final OrdenEstudioRepository ordenes; private final DetalleOrdenEstudioRepository detalles; private final PacienteRepository pacientes; private final EmpresaRepository empresas; private final JdbcTemplate jdbc; private final JasperPdfService jasper;
 public OrdenEstudioService(OrdenEstudioRepository o,DetalleOrdenEstudioRepository d,PacienteRepository p,EmpresaRepository emp,JdbcTemplate j,JasperPdfService jasper){ordenes=o;detalles=d;pacientes=p;empresas=emp;jdbc=j;this.jasper=jasper;}
 public List<OrdenEstudio> listar(UUID e,UUID p){return ordenes.findByEmpresaIdAndPacienteIdOrderByCreadoEnDesc(e,p);} public List<DetalleOrdenEstudio> estudios(UUID id){return detalles.findByOrdenId(id);}
 public byte[] generarPdfJasper(UUID e,UUID id){OrdenEstudio o=buscar(e,id);Paciente p=pacientes.findByIdAndEmpresaId(o.getPacienteId(),e).orElseThrow();Map<String,Object> x=new HashMap<>();x.put("CLINICA",empresas.findById(e).map(Empresa::getNombre).orElse("CLÍNICA MÉDICA"));x.put("NUMERO",o.getNumero());x.put("FECHA",o.getEmitidoEn()==null?"-":o.getEmitidoEn().format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));x.put("PACIENTE",p.getNombreCompleto());x.put("DOCUMENTO",p.getDocumento());x.put("DIAGNOSTICO",valor(o.getIndicacionesClinicas()));x.put("PREPARACION",valor(o.getPreparacionInstrucciones()));x.put("OBSERVACIONES",valor(o.getObservaciones()));List<Map<String,Object>> filas=new ArrayList<>();int n=1;for(DetalleOrdenEstudio d:estudios(id)){Map<String,Object> f=new HashMap<>();f.put("numero",String.valueOf(n++));f.put("descripcion",d.getEstudio());f.put("prioridad",o.getPrioridad());filas.add(f);}return jasper.generar("orden-medica",x,filas);}
 @Transactional public OrdenEstudio crear(UUID e,UUID p,UUID u,UUID dx,String pr,String i,String prep,String ob,String estado,List<Estudio> es){OrdenEstudio o=base(e,p,u,dx,pr,i,prep,ob,estado);o=ordenes.save(o);guardar(o,es);if("EMITIDA".equals(estado))emitir(o);return o;}
 @Transactional public void actualizar(UUID e,UUID id,UUID dx,String pr,String i,String prep,String ob,String estado,List<Estudio> es){OrdenEstudio o=buscar(e,id);if(!"BORRADOR".equals(o.getEstado()))throw new IllegalArgumentException("Solo se pueden editar órdenes en borrador.");o.setDiagnosticoId(dx);o.setPrioridad(pr);o.setIndicacionesClinicas(i);o.setPreparacionInstrucciones(prep);o.setObservaciones(ob);detalles.deleteByOrdenId(id);guardar(o,es);if("EMITIDA".equals(estado))emitir(o);else ordenes.save(o);}
 private OrdenEstudio base(UUID e,UUID p,UUID u,UUID dx,String pr,String i,String prep,String ob,String st){OrdenEstudio o=new OrdenEstudio();o.setEmpresaId(e);o.setPacienteId(p);o.setCreadoPor(u);o.setDiagnosticoId(dx);o.setPrioridad(pr);o.setIndicacionesClinicas(i);o.setPreparacionInstrucciones(prep);o.setObservaciones(ob);o.setEstado(st);o.setCreadoEn(LocalDateTime.now());o.setActualizadoEn(LocalDateTime.now());return o;}
 private void emitir(OrdenEstudio o){if(o.getNumero()==null){Integer n=jdbc.queryForObject("INSERT INTO contador_ordenes_estudios(empresa_id,ultimo_numero) VALUES (?,1) ON CONFLICT(empresa_id) DO UPDATE SET ultimo_numero=contador_ordenes_estudios.ultimo_numero+1 RETURNING ultimo_numero",Integer.class,o.getEmpresaId());o.setNumero("ORD-"+Year.now()+"-"+String.format("%06d",n));}o.setEstado("EMITIDA");o.setEmitidoEn(LocalDateTime.now());ordenes.save(o);com.vaadin.flow.component.UI ui=com.vaadin.flow.component.UI.getCurrent();if(ui!=null)ui.getPage().open("/ordenes-estudios/"+o.getId()+"/pdf","_blank");}
 private OrdenEstudio buscar(UUID e,UUID id){return ordenes.findById(id).filter(o->e.equals(o.getEmpresaId())).orElseThrow(()->new IllegalArgumentException("Orden no encontrada."));}
 private void guardar(OrdenEstudio o,List<Estudio> es){if(es==null||es.isEmpty())throw new IllegalArgumentException("Debe seleccionar al menos un estudio.");for(Estudio x:es){DetalleOrdenEstudio d=new DetalleOrdenEstudio();d.setOrdenId(o.getId());d.setTipo(x.tipo());d.setEstudio(x.nombre());d.setEstado("PENDIENTE");d.setCreadoEn(LocalDateTime.now());d.setActualizadoEn(LocalDateTime.now());detalles.save(d);}}
 public byte[] generarPdf(UUID e,UUID id){OrdenEstudio o=buscar(e,id);try{Paciente p=pacientes.findByIdAndEmpresaId(o.getPacienteId(),e).orElseThrow();ByteArrayOutputStream b=new ByteArrayOutputStream();Document d=new Document(PageSize.A4,42,42,42,42);PdfWriter.getInstance(d,b);d.open();java.awt.Color azul=new java.awt.Color(12,54,120),fondo=new java.awt.Color(238,244,255);String clinica=empresas.findById(e).map(Empresa::getNombre).orElse("CLÍNICA MÉDICA");d.add(new Paragraph(clinica,FontFactory.getFont(FontFactory.HELVETICA_BOLD,16,azul)));d.add(new Paragraph("ORDEN MÉDICA",FontFactory.getFont(FontFactory.HELVETICA_BOLD,25,azul)));PdfPTable cab=new PdfPTable(new float[]{2,1});cab.setWidthPercentage(100);cab.addCell(celda("PACIENTE\n"+p.getNombreCompleto()+"\nCédula: "+valor(p.getDocumento())+"\nSexo: "+valor(p.getGenero()),fondo,azul));cab.addCell(celda("NÚMERO\n"+o.getNumero()+"\n\nFECHA DE EMISIÓN\n"+o.getEmitidoEn().format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")),fondo,azul));d.add(cab);d.add(new Paragraph("\nDIAGNÓSTICO / INDICACIÓN CLÍNICA",FontFactory.getFont(FontFactory.HELVETICA_BOLD,13,azul)));d.add(celda(""+valor(o.getIndicacionesClinicas()),fondo,azul));d.add(new Paragraph("\nESTUDIOS SOLICITADOS",FontFactory.getFont(FontFactory.HELVETICA_BOLD,13,azul)));PdfPTable t=new PdfPTable(new float[]{1,5,2});t.setWidthPercentage(100);for(String h:List.of("#","ESTUDIO","PRIORIDAD"))t.addCell(celda(h,azul,java.awt.Color.WHITE));int n=1;for(DetalleOrdenEstudio x:estudios(id)){t.addCell(celda(""+n++,java.awt.Color.WHITE,azul));t.addCell(celda(x.getEstudio(),java.awt.Color.WHITE,azul));t.addCell(celda(o.getPrioridad(),java.awt.Color.WHITE,azul));}d.add(t);PdfPTable notas=new PdfPTable(2);notas.setWidthPercentage(100);notas.addCell(celda("PREPARACIÓN / INDICACIONES\n"+valor(o.getPreparacionInstrucciones()),fondo,azul));notas.addCell(celda("OBSERVACIONES\n"+valor(o.getObservaciones()),fondo,azul));d.add(notas);d.add(new Paragraph("\n\n                 __________________________\n                   Firma del médico",FontFactory.getFont(FontFactory.HELVETICA_BOLD,11,azul)));d.close();return b.toByteArray();}catch(Exception x){throw new IllegalStateException("No se pudo generar el PDF.",x);}} private PdfPCell celda(String texto,java.awt.Color fondo,java.awt.Color color){PdfPCell c=new PdfPCell(new Paragraph(texto,FontFactory.getFont(FontFactory.HELVETICA,10,color)));c.setPadding(10);c.setBackgroundColor(fondo);c.setBorderColor(azulClaro());return c;}private java.awt.Color azulClaro(){return new java.awt.Color(180,198,225);} private String valor(String s){return s==null||s.isBlank()?"-":s;}
 @Transactional public void registrarResultado(UUID e,UUID id,UUID u,LocalDate f,String r,String ob,String c,String a){DetalleOrdenEstudio d=detalles.findById(id).orElseThrow(()->new IllegalArgumentException("Estudio no encontrado."));buscar(e,d.getOrdenId());d.setFechaResultado(f==null?LocalDate.now():f);d.setResultado(r);d.setObservacionesResultado(ob);d.setCentroRealizador(c);d.setRegistradoPor(u);d.setActualizadoEn(LocalDateTime.now());d.setEstado("RESULTADO DISPONIBLE");detalles.save(d);} public record Estudio(String tipo,String nombre){}
}
