package com.citacloud.app.services;

import com.citacloud.app.models.*;
import com.citacloud.app.repositories.*;
import com.citacloud.app.security.AuthService;
import com.citacloud.app.security.TenantUserDetails;
import jakarta.persistence.EntityManager;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.text.NumberFormat;
import java.util.*;

@Service
public class PagoService {
    public record Aplicacion(UUID cargoId, BigDecimal monto) {}
    public record Solicitud(UUID pacienteId, UUID sucursalId, String metodo, BigDecimal monto, BigDecimal efectivoRecibido,
                            String referencia, String autorizacion, String nota, String claveIdempotencia, List<Aplicacion> aplicaciones) {}
    public record Resumen(BigDecimal totalRecibido, long pagos, BigDecimal pendiente, BigDecimal reembolsado) {}
    private final PagoRepository pagos; private final CargoFinancieroRepository cargos; private final PagoAplicacionRepository aplicaciones;
    private final ReembolsoPagoRepository reembolsos; private final PacienteRepository pacientes; private final SucursalRepository sucursales;
    private final AuditoriaService auditoria; private final JasperPdfService jasper; private final EmpresaRepository empresas; private final UsuarioRepository usuarios; private final EntityManager em; private final NotificacionService notificaciones; private final CajaService caja;
    public PagoService(PagoRepository pagos, CargoFinancieroRepository cargos, PagoAplicacionRepository aplicaciones, ReembolsoPagoRepository reembolsos, PacienteRepository pacientes, SucursalRepository sucursales, AuditoriaService auditoria, JasperPdfService jasper, EmpresaRepository empresas, UsuarioRepository usuarios, EntityManager em, NotificacionService notificaciones, CajaService caja){this.pagos=pagos;this.cargos=cargos;this.aplicaciones=aplicaciones;this.reembolsos=reembolsos;this.pacientes=pacientes;this.sucursales=sucursales;this.auditoria=auditoria;this.jasper=jasper;this.empresas=empresas;this.usuarios=usuarios;this.em=em;this.notificaciones=notificaciones;this.caja=caja;}
    @Transactional(readOnly=true) public List<Pago> listar(UUID empresa){return empresa==null?List.of():pagos.findByEmpresaIdOrderByCreadoEnDesc(empresa);}
    @Transactional(readOnly=true) public Pago obtener(UUID empresa,UUID pagoId){return pagos.findByIdAndEmpresaId(pagoId,empresa).orElseThrow(()->new IllegalArgumentException("Pago no encontrado para esta empresa."));}
    @Transactional(readOnly=true) public List<PagoAplicacion> aplicaciones(UUID empresa,UUID pagoId){obtener(empresa,pagoId);return aplicaciones.findByEmpresaIdAndPagoId(empresa,pagoId);}
    @Transactional(readOnly=true) public BigDecimal totalReembolsado(UUID empresa,UUID pagoId){obtener(empresa,pagoId);return dinero(reembolsos.totalPorPago(empresa,pagoId));}
    @Transactional(readOnly=true) public BigDecimal disponibleReembolso(UUID empresa,UUID pagoId){Pago pago=obtener(empresa,pagoId);return dinero(n(pago.getMonto()).subtract(totalReembolsado(empresa,pagoId)).max(BigDecimal.ZERO));}
    @Transactional(readOnly=true) public byte[] generarRecibo(UUID empresa,UUID pagoId){
        Pago pago=obtener(empresa,pagoId); Empresa entidad=empresas.findById(empresa).orElseThrow(()->new IllegalArgumentException("Empresa no encontrada."));
        List<PagoAplicacion> aplicacionesPago=aplicaciones(empresa,pagoId); NumberFormat moneda=NumberFormat.getNumberInstance(Locale.US); moneda.setMinimumFractionDigits(2); moneda.setMaximumFractionDigits(2);
        List<Map<String,Object>> filas=aplicacionesPago.stream().map(a->{Map<String,Object> fila=new HashMap<>();fila.put("concepto",valor(a.getCargo().getConcepto(),"Cargo financiero"));fila.put("referencia",valor(a.getCargo().getReferenciaOrigen(),""));fila.put("monto",moneda.format(n(a.getMonto())));return fila;}).toList();
        if(filas.isEmpty()){Map<String,Object> fila=new HashMap<>();fila.put("concepto",pago.getFactura()==null?"Pago recibido":"Factura "+valor(pago.getFactura().getNumero(),"sin número"));fila.put("referencia","");fila.put("monto",moneda.format(n(pago.getMonto())));filas=List.of(fila);}
        BigDecimal totalCargos=aplicacionesPago.stream().map(a->n(a.getCargo().getMontoOriginal())).reduce(BigDecimal.ZERO,BigDecimal::add);
        BigDecimal pagadoAnterior=aplicacionesPago.stream().map(a->n(a.getCargo().getMontoPagado()).subtract(n(a.getMonto())).max(BigDecimal.ZERO)).reduce(BigDecimal.ZERO,BigDecimal::add);
        BigDecimal saldoPendiente=aplicacionesPago.stream().map(a->n(a.getCargo().getSaldo())).reduce(BigDecimal.ZERO,BigDecimal::add);
        BigDecimal reembolsado=n(reembolsos.totalPorPago(empresa,pagoId)); String numero=valor(pago.getNumero(),"PAG-"+pago.getId().toString().substring(0,8).toUpperCase(Locale.ROOT));
        Usuario recibidoPor=pago.getUsuarioId()==null?null:usuarios.findByIdAndEmpresaId(pago.getUsuarioId(),empresa).orElse(null); Paciente paciente=pago.getPaciente(); Sucursal sucursal=pago.getSucursal();
        Map<String,Object> parametros=new HashMap<>(); parametros.put("CLINICA",valor(entidad.getNombre(),"CitaCloud"));parametros.put("RNC",valor(entidad.getRncIdentificacion(),""));parametros.put("DIRECCION",valor(sucursal==null?entidad.getDireccion():sucursal.getDireccion(),""));parametros.put("TELEFONO",valor(sucursal==null?entidad.getTelefono():sucursal.getTelefono(),""));parametros.put("SUCURSAL",sucursal==null?"":valor(sucursal.getNombre(),""));parametros.put("NUMERO",numero);parametros.put("FECHA",pago.getFecha()==null?"—":pago.getFecha().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))+" · "+java.time.LocalTime.now().format(DateTimeFormatter.ofPattern("h:mm a",Locale.US)));
        parametros.put("PACIENTE",paciente==null?"—":nombreCapitalizado(paciente.getNombreCompleto()));parametros.put("EXPEDIENTE",paciente==null?"":valor(paciente.getNumeroExpediente(),""));parametros.put("DOCUMENTO",paciente==null?"":ocultarDocumento(paciente.getDocumento()));parametros.put("ESTADO",estadoVisual(pago.getEstado()));parametros.put("METODO",valor(pago.getMetodoPago(),"—"));parametros.put("REFERENCIA",valor(pago.getReferencia(),""));parametros.put("EFECTIVO",pago.getEfectivoRecibido()==null?"":moneda.format(pago.getEfectivoRecibido()));parametros.put("CAMBIO",pago.getCambio()==null?"":moneda.format(pago.getCambio()));parametros.put("RECIBIDO_POR",recibidoPor==null?"":nombreCapitalizado(recibidoPor.getNombreCompleto()));parametros.put("TOTAL_CARGOS",moneda.format(totalCargos));parametros.put("PAGADO_ANTERIOR",moneda.format(pagadoAnterior));parametros.put("ESTE_PAGO",moneda.format(n(pago.getMonto())));parametros.put("SALDO_PENDIENTE",moneda.format(saldoPendiente));parametros.put("REEMBOLSADO",moneda.format(reembolsado));parametros.put("NOTA",valor(pago.getObservacion(),""));
        auditoria.registrar(empresa,null,"PAGOS","PAYMENT_RECEIPT_PRINTED","PAGO",pagoId,numero,paciente==null?null:paciente.getId(),List.of(),"SUCCESS",null,true); return jasper.generar("recibo-pago",parametros,filas);
    }
    @Transactional(readOnly=true) public List<CargoFinanciero> pendientes(UUID empresa,UUID paciente){return empresa==null||paciente==null?List.of():cargos.findByEmpresaIdAndPacienteIdAndSaldoGreaterThanOrderByFechaAsc(empresa,paciente,BigDecimal.ZERO);}
    @Transactional(readOnly=true) public Resumen resumen(UUID empresa){List<Pago> lista=listar(empresa);BigDecimal recibido=lista.stream().filter(p->!"VOIDED".equals(p.getEstado())).map(Pago::getMonto).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal reembolsado=lista.stream().map(p->n(reembolsos.totalPorPago(empresa,p.getId()))).reduce(BigDecimal.ZERO,BigDecimal::add);return new Resumen(recibido.subtract(reembolsado),lista.stream().filter(p->!"VOIDED".equals(p.getEstado())).count(),n(cargos.saldoPendiente(empresa)),reembolsado);}
    @Transactional public Pago registrar(UUID empresa,Solicitud solicitud){return registrar(empresa,solicitud,null);}
    @Transactional public Pago registrar(UUID empresa,Solicitud solicitud,UUID sesionCajaId){
        validarEmpresa(empresa); if(solicitud==null)throw new IllegalArgumentException("Debe indicar los datos del pago.");
        if(solicitud.claveIdempotencia()!=null&&!solicitud.claveIdempotencia().isBlank()){Optional<Pago> previo=pagos.findByEmpresaIdAndClaveIdempotencia(empresa,solicitud.claveIdempotencia());if(previo.isPresent())return previo.get();}
        Paciente paciente=pacientes.findByIdAndEmpresaId(solicitud.pacienteId(),empresa).orElseThrow(()->new IllegalArgumentException("Paciente no encontrado para esta empresa."));
        Sucursal sucursal=solicitud.sucursalId()==null?null:sucursales.findByIdAndEmpresaId(solicitud.sucursalId(),empresa).orElseThrow(()->new IllegalArgumentException("Sucursal no encontrada para esta empresa."));
        BigDecimal monto=dinero(solicitud.monto()); if(monto.signum()<=0)throw new IllegalArgumentException("El monto debe ser mayor que cero.");
        List<Aplicacion> items=solicitud.aplicaciones()==null?List.of():solicitud.aplicaciones(); if(items.isEmpty())throw new IllegalArgumentException("Seleccione al menos un cargo pendiente.");
        BigDecimal total=items.stream().map(Aplicacion::monto).map(this::dinero).reduce(BigDecimal.ZERO,BigDecimal::add); if(total.compareTo(monto)!=0)throw new IllegalArgumentException("El total aplicado debe coincidir con el monto del pago.");
        String metodo=normalizarMetodo(solicitud.metodo()); BigDecimal recibido=solicitud.efectivoRecibido()==null?null:dinero(solicitud.efectivoRecibido()); if("EFECTIVO".equals(metodo)&&(recibido==null||recibido.compareTo(monto)<0))throw new IllegalArgumentException("El efectivo recibido debe cubrir el monto a pagar."); if("EFECTIVO".equals(metodo))caja.validarPagoEfectivo(empresa,solicitud.sucursalId(),sesionCajaId);
        Pago pago=new Pago(); pago.setEmpresaId(empresa);pago.setNumero(siguienteNumero(empresa));pago.setPaciente(paciente);pago.setSucursal(sucursal);pago.setFecha(LocalDate.now());pago.setMonto(monto);pago.setMetodoPago(metodo);pago.setReferencia(limitar(solicitud.referencia(),120));pago.setAutorizacion(limitar(solicitud.autorizacion(),120));pago.setObservacion(limitar(solicitud.nota(),3000));pago.setEfectivoRecibido(recibido);pago.setCambio("EFECTIVO".equals(metodo)?recibido.subtract(monto):BigDecimal.ZERO);pago.setClaveIdempotencia(limitar(solicitud.claveIdempotencia(),100));TenantUserDetails usuarioActual=AuthService.getAuthenticatedUser();pago.setUsuarioId(usuarioActual==null?null:usuarioActual.getUsuarioId());pago.setEstado("APPLIED");pago=pagos.save(pago);
        for(Aplicacion item:items){CargoFinanciero cargo=cargos.bloquearPorIdYEmpresa(item.cargoId(),empresa).orElseThrow(()->new IllegalArgumentException("Cargo no encontrado para esta empresa."));if(!cargo.getPaciente().getId().equals(paciente.getId()))throw new IllegalArgumentException("El cargo no pertenece al paciente seleccionado.");BigDecimal aplicado=dinero(item.monto());if(aplicado.signum()<=0||aplicado.compareTo(cargo.getSaldo())>0)throw new IllegalArgumentException("El saldo de esta cuenta ha cambiado. Actualiza la información antes de continuar.");if(pago.getFactura()==null&&cargo.getFactura()!=null)pago.setFactura(cargo.getFactura());aplicar(cargo,aplicado);PagoAplicacion aplicacion=new PagoAplicacion();aplicacion.setEmpresaId(empresa);aplicacion.setPago(pago);aplicacion.setCargo(cargo);aplicacion.setMonto(aplicado);aplicaciones.save(aplicacion);}
        caja.registrarPago(pago,sesionCajaId); auditoria.registrar(empresa,null,"PAGOS","PAYMENT_CREATED","PAGO",pago.getId(),pago.getNumero(),paciente.getId(),List.of(new AuditoriaService.Cambio("monto",null,monto.toPlainString()),new AuditoriaService.Cambio("metodo",null,metodo)),"SUCCESS",null,true);notificaciones.crearParaPago(empresa,"PAYMENT_CREATED","Pago registrado",nombreCapitalizado(paciente.getNombreCompleto())+" realizó un pago de "+formatoMonto(monto)+".",pago);return pago;
    }
    @Transactional public void anular(UUID empresa,UUID pagoId,String motivo){Pago pago=pagos.findByIdAndEmpresaId(pagoId,empresa).orElseThrow(()->new IllegalArgumentException("Pago no encontrado para esta empresa."));if(!"APPLIED".equals(pago.getEstado()))throw new IllegalArgumentException("Solo se pueden anular pagos aplicados.");if(motivo==null||motivo.isBlank())throw new IllegalArgumentException("Indique el motivo de la anulación.");for(PagoAplicacion a:aplicaciones.findByEmpresaIdAndPagoId(empresa,pagoId)){CargoFinanciero c=cargos.bloquearPorIdYEmpresa(a.getCargo().getId(),empresa).orElseThrow();revertir(c,a.getMonto());}TenantUserDetails u=AuthService.getAuthenticatedUser();pago.anular(u==null?null:u.getUsuarioId(),limitar(motivo,3000));auditoria.registrar(empresa,null,"PAGOS","PAYMENT_VOIDED","PAGO",pagoId,pago.getNumero(),pago.getPaciente().getId(),List.of(),"SUCCESS",motivo,true);notificaciones.crearParaPago(empresa,"PAYMENT_VOIDED","Pago anulado","El pago "+pago.getNumero()+" por "+formatoMonto(pago.getMonto())+" fue anulado.",pago);}
    @Transactional public void reembolsar(UUID empresa,UUID pagoId,BigDecimal monto,String metodo,String referencia,String motivo){Pago pago=pagos.findByIdAndEmpresaId(pagoId,empresa).orElseThrow(()->new IllegalArgumentException("Pago no encontrado para esta empresa."));if("VOIDED".equals(pago.getEstado()))throw new IllegalArgumentException("No se puede reembolsar un pago anulado.");monto=dinero(monto);BigDecimal yaReembolsado=n(reembolsos.totalPorPago(empresa,pagoId));BigDecimal disponible=pago.getMonto().subtract(yaReembolsado);if(monto.signum()<=0||monto.compareTo(disponible)>0)throw new IllegalArgumentException("El monto supera el importe disponible para reembolso.");if(motivo==null||motivo.isBlank())throw new IllegalArgumentException("Indique el motivo del reembolso.");BigDecimal pendienteReversion=monto;for(PagoAplicacion a:aplicaciones.findByEmpresaIdAndPagoId(empresa,pagoId)){if(pendienteReversion.signum()==0)break;CargoFinanciero c=cargos.bloquearPorIdYEmpresa(a.getCargo().getId(),empresa).orElseThrow();BigDecimal porRevertir=a.getMonto().min(pendienteReversion);revertir(c,porRevertir);pendienteReversion=pendienteReversion.subtract(porRevertir);}ReembolsoPago r=new ReembolsoPago();r.setEmpresaId(empresa);r.setPago(pago);r.setMonto(monto);r.setMetodoPago(normalizarMetodo(metodo));r.setReferencia(limitar(referencia,120));r.setMotivo(limitar(motivo,3000));TenantUserDetails u=AuthService.getAuthenticatedUser();r.setReembolsadoPor(u==null?null:u.getUsuarioId());r=reembolsos.save(r);caja.registrarReembolso(r);pago.setEstado(yaReembolsado.add(monto).compareTo(pago.getMonto())==0?"REFUNDED":"PARTIALLY_REFUNDED");String evento="REFUNDED".equals(pago.getEstado())?"PAYMENT_REFUNDED":"PAYMENT_PARTIALLY_REFUNDED";auditoria.registrar(empresa,null,"PAGOS",evento,"PAGO",pagoId,pago.getNumero(),pago.getPaciente().getId(),List.of(new AuditoriaService.Cambio("monto",null,monto.toPlainString())),"SUCCESS",motivo,true);String mensaje="PAYMENT_REFUNDED".equals(evento)?"El pago "+pago.getNumero()+" por "+formatoMonto(pago.getMonto())+" fue reembolsado.":"Se reembolsaron "+formatoMonto(monto)+" del pago "+pago.getNumero()+".";notificaciones.crearParaPago(empresa,evento,"PAYMENT_REFUNDED".equals(evento)?"Pago reembolsado":"Reembolso parcial",mensaje,pago);}
    private void aplicar(CargoFinanciero c,BigDecimal monto){c.setMontoPagado(dinero(c.getMontoPagado()).add(monto));c.setSaldo(dinero(c.getSaldo()).subtract(monto));c.setEstado(c.getSaldo().signum()==0?"PAGADA":"PARCIAL");cargos.save(c);if(c.getFactura()!=null){Factura f=c.getFactura();f.setMontoPagado(dinero(f.getMontoPagado()).add(monto));f.setSaldo(dinero(f.getSaldo()).subtract(monto));f.setEstado(f.getSaldo().signum()==0?"PAGADA":"PARCIAL");}}
    private void revertir(CargoFinanciero c,BigDecimal monto){c.setMontoPagado(dinero(c.getMontoPagado()).subtract(monto));c.setSaldo(dinero(c.getSaldo()).add(monto));c.setEstado(c.getMontoPagado().signum()==0?"PENDIENTE":"PARCIAL");cargos.save(c);if(c.getFactura()!=null){Factura f=c.getFactura();f.setMontoPagado(dinero(f.getMontoPagado()).subtract(monto));f.setSaldo(dinero(f.getSaldo()).add(monto));f.setEstado(f.getMontoPagado().signum()==0?"PENDIENTE":"PARCIAL");}}
    private String formatoMonto(BigDecimal monto){NumberFormat formato=NumberFormat.getNumberInstance(Locale.US);formato.setMinimumFractionDigits(2);formato.setMaximumFractionDigits(2);return "RD$ "+formato.format(n(monto));} private String siguienteNumero(UUID empresa){em.createNativeQuery("insert into consecutivos_financieros(empresa_id,siguiente_pago) values (?1,1) on conflict (empresa_id) do nothing").setParameter(1,empresa).executeUpdate();Number n=(Number)em.createNativeQuery("update consecutivos_financieros set siguiente_pago=siguiente_pago+1 where empresa_id=?1 returning siguiente_pago-1").setParameter(1,empresa).getSingleResult();return "PAG-%06d".formatted(n.longValue());}
    private void validarEmpresa(UUID empresa){if(empresa==null)throw new IllegalArgumentException("No existe una empresa autenticada.");} private BigDecimal dinero(BigDecimal v){return v==null?BigDecimal.ZERO:v.setScale(2,RoundingMode.HALF_UP);} private BigDecimal n(BigDecimal v){return v==null?BigDecimal.ZERO:v;} private <T>T valor(T valor,T predeterminado){return valor==null?predeterminado:valor;} private String nombreCapitalizado(String nombre){if(nombre==null||nombre.isBlank())return "—";return Arrays.stream(nombre.trim().toLowerCase(Locale.ROOT).split("\\s+")).filter(p->!p.isBlank()).map(p->Character.toUpperCase(p.charAt(0))+p.substring(1)).collect(java.util.stream.Collectors.joining(" "));} private String ocultarDocumento(String documento){if(documento==null||documento.isBlank())return "";String limpio=documento.trim();return limpio.length()<=4?"****":"****"+limpio.substring(limpio.length()-4);} private String estadoVisual(String estado){return switch(valor(estado,"APPLIED")){case "VOIDED"->"ANULADO";case "REFUNDED"->"REEMBOLSADO";case "PARTIALLY_REFUNDED"->"PARCIALMENTE REEMBOLSADO";default->"APLICADO";};} private String normalizarMetodo(String v){String x=v==null?"":v.trim().toUpperCase(Locale.ROOT);if(!Set.of("EFECTIVO","TARJETA","TRANSFERENCIA","CHEQUE","OTRO").contains(x))throw new IllegalArgumentException("Método de pago no válido.");return x;} private String limitar(String v,int max){return v==null?null:v.length()<=max?v:v.substring(0,max);}
}
