package com.citacloud.app.services;
import com.citacloud.app.models.SignosVitales;
import com.citacloud.app.repositories.*;
import org.springframework.stereotype.Service;
import java.math.*;
import java.time.LocalDateTime;
import java.util.*;
@Service public class SignosVitalesService {
    private final SignosVitalesRepository repo; private final PacienteRepository pacientes;
    public SignosVitalesService(SignosVitalesRepository r,PacienteRepository p){repo=r;pacientes=p;}
    public List<SignosVitales> listarPorPaciente(UUID empresa,UUID paciente){return repo.findByEmpresaIdAndPacienteIdOrderByIdDesc(empresa,paciente);}
    public SignosVitales registrar(UUID empresa,UUID paciente,BigDecimal peso,BigDecimal altura,BigDecimal temp,Integer sistolica,Integer diastolica){return registrarCompleto(empresa,paciente,null,peso,altura,temp,sistolica,diastolica,null,null,null,null,null,null,null);}
    public SignosVitales registrarCompleto(UUID empresa,UUID paciente,UUID usuario,BigDecimal peso,BigDecimal altura,BigDecimal temp,Integer sistolica,Integer diastolica,Integer pulso,Integer respiratoria,BigDecimal saturacion,BigDecimal glucemia,BigDecimal abdomen,Integer dolor,String observaciones){pacientes.findByIdAndEmpresaId(paciente,empresa).orElseThrow(()->new IllegalArgumentException("Paciente no encontrado para esta empresa.")); SignosVitales s=new SignosVitales();s.setEmpresaId(empresa);s.setPacienteId(paciente);s.setUsuarioId(usuario);s.setFecha(LocalDateTime.now());return guardar(s,peso,altura,temp,sistolica,diastolica,pulso,respiratoria,saturacion,glucemia,abdomen,dolor,observaciones);}
    public SignosVitales actualizar(UUID empresa,UUID id,BigDecimal peso,BigDecimal altura,BigDecimal temp,Integer sistolica,Integer diastolica){SignosVitales s=repo.findById(id).filter(x->empresa.equals(x.getEmpresaId())).orElseThrow(()->new IllegalArgumentException("Registro no encontrado para esta empresa."));return guardar(s,peso,altura,temp,sistolica,diastolica,s.getFrecuenciaCardiaca(),s.getFrecuenciaRespiratoria(),s.getSaturacionOxigeno(),s.getGlucemia(),s.getCircunferenciaAbdominal(),s.getNivelDolor(),s.getObservaciones());}
    public SignosVitales actualizarCompleto(UUID empresa,UUID id,BigDecimal peso,BigDecimal altura,BigDecimal temp,Integer sistolica,Integer diastolica,Integer pulso,Integer respiratoria,BigDecimal saturacion,BigDecimal glucemia,BigDecimal abdomen,Integer dolor,String observaciones){SignosVitales s=repo.findById(id).filter(x->empresa.equals(x.getEmpresaId())).orElseThrow(()->new IllegalArgumentException("Registro no encontrado para esta empresa."));return guardar(s,peso,altura,temp,sistolica,diastolica,pulso,respiratoria,saturacion,glucemia,abdomen,dolor,observaciones);}
    private SignosVitales guardar(SignosVitales s,BigDecimal peso,BigDecimal altura,BigDecimal temp,Integer sistolica,Integer diastolica,Integer pulso,Integer respiratoria,BigDecimal saturacion,BigDecimal glucemia,BigDecimal abdomen,Integer dolor,String observaciones){if(peso==null||altura==null||peso.signum()<=0||altura.signum()<=0)throw new IllegalArgumentException("Peso y altura válidos son obligatorios.");if(dolor!=null&&(dolor<0||dolor>10))throw new IllegalArgumentException("El nivel de dolor debe estar entre 0 y 10.");s.setPeso(peso);s.setAltura(altura);s.setTemperatura(temp);s.setPresionSistolica(sistolica);s.setPresionDiastolica(diastolica);s.setFrecuenciaCardiaca(pulso);s.setFrecuenciaRespiratoria(respiratoria);s.setSaturacionOxigeno(saturacion);s.setGlucemia(glucemia);s.setCircunferenciaAbdominal(abdomen);s.setNivelDolor(dolor);s.setObservaciones(observaciones);s.setImc(peso.divide(altura.multiply(altura),2,RoundingMode.HALF_UP));return repo.save(s);}
}
