package com.citacloud.app.views;

import com.citacloud.app.models.*;
import com.citacloud.app.repositories.UsuarioRepository;
import com.citacloud.app.security.*;
import com.citacloud.app.services.AuditoriaService;
import com.vaadin.flow.component.*;
import com.vaadin.flow.component.button.*;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.*;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.*;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.router.*;
import jakarta.annotation.security.PermitAll;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;

@Route(value="auditoria",layout=MainLayout.class) @PageTitle("Auditoría | CitaCloud") @PermitAll
public class AuditoriaView extends VerticalLayout implements BeforeEnterObserver {
    private final AuditoriaService audit; private final UsuarioRepository users; private final TenantUserDetails session; private final UUID empresa;
    private final Grid<AuditoriaEvento> grid=new Grid<>(AuditoriaEvento.class,false); private final TextField search=new TextField();
    private final DatePicker desde=new DatePicker("Fecha desde"), hasta=new DatePicker("Fecha hasta"); private final ComboBox<String> module=new ComboBox<>("Módulo"), result=new ComboBox<>("Resultado"); private final ComboBox<Usuario> user=new ComboBox<>("Usuario");
    private final Div cards=new Div(); private final ComboBox<Integer> filas=new ComboBox<>(); private final Span resumen=new Span(); private final Button anterior=new Button(VaadinIcon.ANGLE_LEFT.create()), siguiente=new Button(VaadinIcon.ANGLE_RIGHT.create());
    private int pagina; private long total; private static final DateTimeFormatter F=DateTimeFormatter.ofPattern("dd/MM/uu HH:mm");

    public AuditoriaView(AuditoriaService audit,UsuarioRepository users){this.audit=audit;this.users=users;session=AuthService.getAuthenticatedUser();empresa=session==null?null:session.getEmpresaId();setWidthFull();setPadding(true);getStyle().set("height","auto").set("min-height","100%").set("padding-bottom","5rem");add(header(),cards,filters(),actividad());configurar();buscar();}
    @Override public void beforeEnter(BeforeEnterEvent e){if(!can("AUDIT_VIEW")&&!can("MENU_AUDITORIA"))e.forwardTo("");}

    private Component header(){H2 h=new H2("Auditoría");h.getStyle().set("margin","0");VerticalLayout texto=new VerticalLayout(h,new Paragraph("Registro de actividades y cambios realizados dentro de CitaCloud."));texto.setPadding(false);texto.setSpacing(false);Button buscar=new Button(VaadinIcon.SEARCH.create(),e->buscar());buscar.setTooltipText("Buscar");buscar.addThemeVariants(ButtonVariant.LUMO_PRIMARY);buscar.getStyle().set("background-color","#2563eb").set("color","#ffffff");Button limpiar=new Button(VaadinIcon.ERASER.create(),e->limpiarFiltros());limpiar.setTooltipText("Limpiar");limpiar.getStyle().set("background-color","#e2e8f0").set("color","#334155");HorizontalLayout acciones=new HorizontalLayout(buscar,limpiar);acciones.setSpacing(false);acciones.getStyle().set("gap","0.35rem");HorizontalLayout cabecera=new HorizontalLayout(texto,acciones);cabecera.setWidthFull();cabecera.setAlignItems(FlexComponent.Alignment.START);cabecera.setJustifyContentMode(FlexComponent.JustifyContentMode.BETWEEN);return cabecera;}
    private Component filters(){search.setLabel("Buscar");search.setPlaceholder("Buscar por recurso, módulo o acción...");search.setPrefixComponent(VaadinIcon.SEARCH.create());search.setClearButtonVisible(true);search.setWidth("360px");desde.setValue(LocalDate.now().minusDays(30));hasta.setValue(LocalDate.now());desde.setWidth("170px");hasta.setWidth("170px");user.setItems(empresa==null?List.of():users.findByEmpresaId(empresa));user.setItemLabelGenerator(Usuario::getNombreCompleto);user.setClearButtonVisible(true);user.setWidth("200px");module.setItems("PACIENTES","CITAS","DOCUMENTOS","USUARIOS","ROLES","CONFIGURACION","FACTURACION","PAGOS");result.setItems("SUCCESS","FAILED","DENIED");for(ComboBox<String>x:List.of(module,result)){x.setClearButtonVisible(true);x.setWidth("170px");}HorizontalLayout h=new HorizontalLayout(search,desde,hasta,user,module,result);h.setWidthFull();h.setAlignItems(FlexComponent.Alignment.END);h.getStyle().set("background-color","#ffffff").set("padding","1rem").set("flex-wrap","wrap").set("border-radius","12px").set("border","1px solid #e2e8f0");return h;}
    private Component actividad(){grid.addColumn(e->F.format(e.getFecha())).setHeader("Fecha/Hora").setAutoWidth(true);grid.addColumn(e->userName(e.getUsuarioId())).setHeader("Usuario");grid.addColumn(AuditoriaEvento::getModulo).setHeader("Módulo");grid.addColumn(e->label(e.getAccion())).setHeader("Acción");grid.addColumn(e->e.getRecurso()==null?e.getEntidad():e.getRecurso()).setHeader("Recurso").setFlexGrow(1);grid.addColumn(e->resultLabel(e.getResultado())).setHeader("Resultado");grid.addItemClickListener(e->details(e.getItem()));grid.setAllRowsVisible(true);grid.setWidthFull();VerticalLayout contenido=new VerticalLayout(grid,paginador());contenido.setPadding(false);contenido.setSpacing(true);return contenido;}
    private Component paginador(){filas.setLabel("Filas por página");filas.setItems(15,25,50,100);filas.setValue(15);filas.setWidth("150px");filas.setAllowCustomValue(false);filas.addValueChangeListener(e->buscar());anterior.setTooltipText("Página anterior");siguiente.setTooltipText("Página siguiente");anterior.addThemeVariants(ButtonVariant.LUMO_TERTIARY);siguiente.addThemeVariants(ButtonVariant.LUMO_TERTIARY);anterior.addClickListener(e->{pagina--;actualizarTabla();});siguiente.addClickListener(e->{pagina++;actualizarTabla();});HorizontalLayout navegacion=new HorizontalLayout(resumen,anterior,siguiente);navegacion.setAlignItems(FlexComponent.Alignment.END);HorizontalLayout pie=new HorizontalLayout(filas,navegacion);pie.setWidthFull();pie.setAlignItems(FlexComponent.Alignment.END);pie.setJustifyContentMode(FlexComponent.JustifyContentMode.BETWEEN);pie.getStyle().set("padding","0.65rem 0.85rem").set("margin-bottom","1.25rem").set("background","#ffffff").set("border","1px solid #e2e8f0").set("border-radius","10px");return pie;}
    private void configurar(){}
    private void buscar(){pagina=0;actualizarTabla();}
    private void actualizarTabla(){if(empresa==null)return;LocalDate[] r=rango();if(r[0].isAfter(r[1])){resumen.setText("La fecha desde no puede ser posterior a la fecha hasta.");grid.setItems(List.of());return;}AuditoriaService.Pagina datos=audit.buscarPagina(empresa,r[0],r[1],user.getValue()==null?null:user.getValue().getId(),module.getValue(),result.getValue(),search.getValue(),pagina,filas.getValue()==null?15:filas.getValue());total=datos.total();int tamanio=filas.getValue()==null?15:filas.getValue();int paginas=Math.max(1,(int)Math.ceil((double)total/tamanio));if(pagina>=paginas){pagina=paginas-1;datos=audit.buscarPagina(empresa,r[0],r[1],user.getValue()==null?null:user.getValue().getId(),module.getValue(),result.getValue(),search.getValue(),pagina,tamanio);}grid.setItems(datos.eventos());long inicio=total==0?0:(long)pagina*tamanio+1;long fin=Math.min((pagina+1L)*tamanio,total);resumen.setText(total==0?"Sin registros":"Mostrando "+inicio+"–"+fin+" de "+total);anterior.setEnabled(pagina>0);siguiente.setEnabled(pagina<paginas-1);AuditoriaService.Resumen s=audit.resumen(empresa,r[0],r[1]);cards.removeAll();cards.add(new HorizontalLayout(card("Eventos hoy",s.eventosHoy()),card("Usuarios",s.usuarios()),card("Cambios",s.cambios()),card("Accesos sensibles",s.accesosSensibles())));}
    private void limpiarFiltros(){search.clear();user.clear();module.clear();result.clear();desde.setValue(LocalDate.now().minusDays(30));hasta.setValue(LocalDate.now());buscar();}
    private Div card(String t,long n){Div d=new Div(new Span(t),new H3(String.valueOf(n)));d.getStyle().set("min-width","160px").set("padding","1rem").set("border","1px solid var(--lumo-contrast-10pct)").set("border-radius","var(--lumo-border-radius-m)");return d;}
    private LocalDate[] rango(){return new LocalDate[]{desde.getValue()==null?LocalDate.of(2000,1,1):desde.getValue(),hasta.getValue()==null?LocalDate.now():hasta.getValue()};}
    private void details(AuditoriaEvento e){if(!can("AUDIT_VIEW_DETAILS")&&!can("MENU_AUDITORIA"))return;Dialog d=new Dialog();H3 titulo=new H3("Detalle de auditoría");titulo.getStyle().set("margin","0");d.getHeader().add(titulo);d.setWidth("min(96vw, 980px)");d.setMaxHeight("85vh");FormLayout datos=new FormLayout();datos.setResponsiveSteps(new FormLayout.ResponsiveStep("0",3));datos.add(dato("Evento",label(e.getAccion())),dato("Resultado",resultLabel(e.getResultado())),dato("Fecha y hora",F.format(e.getFecha())),dato("Usuario",userName(e.getUsuarioId())),dato("Rol",value(e.getRolUsuario())),dato("Módulo",value(e.getModulo())),dato("Recurso",value(e.getRecurso())),dato("Motivo",value(e.getMotivo())),dato("IP",maskIp(e.getIp())),dato("Dispositivo",value(e.getDispositivo())),dato("ID del evento","AUD-"+e.getId().toString().substring(0,8).toUpperCase()));if(e.getDatosAnteriores()!=null||e.getDatosNuevos()!=null){datos.add(dato("Valor anterior",value(e.getDatosAnteriores())),dato("Valor nuevo",value(e.getDatosNuevos())));}d.add(datos);d.getFooter().add(new Button("Cerrar",x->d.close()));d.open();}
    private Div dato(String etiqueta,String contenido){Span titulo=new Span(etiqueta);titulo.getStyle().set("font-size","0.78rem").set("font-weight","700").set("color","var(--lumo-secondary-text-color)");Span valor=new Span(contenido);valor.getStyle().set("white-space","pre-line").set("word-break","break-word").set("font-size","1rem");Div bloque=new Div(titulo,valor);bloque.getStyle().set("display","flex").set("flex-direction","column").set("gap","0.25rem").set("padding","0.45rem 0");return bloque;} private String userName(UUID id){return id==null?"Sistema":users.findByIdAndEmpresaId(id,empresa).map(Usuario::getNombreCompleto).orElse("Usuario no disponible");} private String label(String x){return x==null?"—":x.replace('_',' ');} private String resultLabel(String x){return "SUCCESS".equals(x)?"✓ Exitoso":"DENIED".equals(x)?"⚠ Denegado":"✕ Fallido";} private String value(String x){return x==null||x.isBlank()?"—":x;} private String maskIp(String x){if(x==null)return "—";String[] p=x.split("\\.");return p.length==4?p[0]+"."+p[1]+".xxx.xxx":x;} private boolean can(String p){return session!=null&&session.getAuthorities().stream().anyMatch(a->p.equals(a.getAuthority())||"ROLE_ADMINISTRADOR".equals(a.getAuthority())||"ROLE_SUPERADMIN".equals(a.getAuthority()));}
}
