package com.citacloud.app.views;
import com.vaadin.flow.component.Component; import com.vaadin.flow.component.formlayout.FormLayout;
import com.citacloud.app.models.*; import com.citacloud.app.repositories.UsuarioRepository; import com.citacloud.app.security.*; import com.citacloud.app.services.*; import com.vaadin.flow.component.button.*; import com.vaadin.flow.component.combobox.*; import com.vaadin.flow.component.dialog.Dialog; import com.vaadin.flow.component.grid.Grid; import com.vaadin.flow.component.html.*; import com.vaadin.flow.component.icon.*; import com.vaadin.flow.component.notification.Notification; import com.vaadin.flow.component.orderedlayout.*; import com.vaadin.flow.component.textfield.*; import com.vaadin.flow.router.*; import jakarta.annotation.security.PermitAll; import java.util.*;
@Route(value="cajas",layout=MainLayout.class) @PageTitle("Cajas | CitaCloud") @PermitAll
public class CajasView extends VerticalLayout {
 private final CajaService servicio; private final SucursalService sucursales; private final UsuarioRepository usuarios; private final UUID empresa; private final Grid<Caja> tabla=new Grid<>(Caja.class,false);
 public CajasView(CajaService servicio,SucursalService sucursales,UsuarioRepository usuarios){this.servicio=servicio;this.sucursales=sucursales;this.usuarios=usuarios;TenantUserDetails u=AuthService.getAuthenticatedUser();empresa=u==null?null:u.getEmpresaId();setWidthFull();add(new H2("Cajas"),barra(),tabla);cargar();}
private Component barra(){Button nueva=new Button(new Icon(VaadinIcon.PLUS),e->dialogo(null));nueva.setTooltipText("Nueva caja");nueva.addThemeVariants(ButtonVariant.LUMO_PRIMARY);nueva.getStyle().set("background-color","#16a34a").set("color","#ffffff");HorizontalLayout b=new HorizontalLayout(new Span("Administra cajas, estados y usuarios autorizados."),nueva);b.setWidthFull();b.setJustifyContentMode(JustifyContentMode.BETWEEN);return b;}
 private void cargar(){tabla.setWidthFull();tabla.addColumn(Caja::getCodigo).setHeader("Código");tabla.addColumn(Caja::getNombre).setHeader("Nombre");tabla.addColumn(c->c.getSucursal()==null?"—":c.getSucursal().getNombre()).setHeader("Sucursal");tabla.addColumn(c->c.getUsuarios().size()).setHeader("Usuarios asignados");tabla.addComponentColumn(c->{Button editar=new Button(VaadinIcon.EDIT.create(),e->dialogo(c));editar.setTooltipText("Editar caja");editar.addThemeVariants(ButtonVariant.LUMO_TERTIARY_INLINE);editar.getStyle().set("background","transparent").set("border","none").set("box-shadow","none").set("padding","0");Button estado=new Button(c.isActiva()?"Desactivar":"Activar",e->{try{servicio.activar(empresa,c.getId(),!c.isActiva());cargarDatos();}catch(Exception x){error(x);}});return new HorizontalLayout(editar,estado);}).setHeader("Acciones");cargarDatos();}
 private void cargarDatos(){try{tabla.setItems(servicio.cajas(empresa));tabla.setAllRowsVisible(true);}catch(Exception e){error(e);}}
 private void dialogo(Caja existente){Dialog d=new Dialog();d.setWidth("min(760px,96vw)");d.setHeaderTitle(existente==null?"Nueva caja":"Editar caja");TextField codigo=new TextField("Código"),nombre=new TextField("Nombre *"),descripcion=new TextField("Descripción");codigo.setVisible(existente!=null);ComboBox<Sucursal> sucursal=new ComboBox<>("Sucursal *");sucursal.setItems(sucursales.listarActivas(empresa));sucursal.setItemLabelGenerator(Sucursal::getNombre);MultiSelectComboBox<Usuario> asignados=new MultiSelectComboBox<>("Usuarios asignados");List<Usuario> elegibles=usuarios.findByEmpresaId(empresa).stream().filter(Usuario::getActivo).toList();asignados.setItems(elegibles);asignados.setItemLabelGenerator(u->u.getNombre()+" "+u.getApellido()+" ("+u.getUsuario()+")");if(existente!=null){codigo.setValue(existente.getCodigo());nombre.setValue(existente.getNombre());descripcion.setValue(Optional.ofNullable(existente.getDescripcion()).orElse(""));sucursal.setValue(existente.getSucursal());asignados.setValue(new HashSet<>(existente.getUsuarios()));}Button guardar=new Button(new Icon(VaadinIcon.DISC),e->{try{Caja c=existente==null?servicio.crearCaja(empresa,sucursal.getValue().getId(),"",nombre.getValue(),descripcion.getValue()):existente;if(existente!=null){c.setCodigo(codigo.getValue());c.setNombre(nombre.getValue());c.setDescripcion(descripcion.getValue());}servicio.asignarUsuarios(empresa,c.getId(),asignados.getValue().stream().map(Usuario::getId).toList());d.close();cargarDatos();}catch(Exception x){error(x);}});guardar.setTooltipText("Guardar");guardar.addThemeVariants(ButtonVariant.LUMO_PRIMARY);guardar.getStyle().set("background-color","#16a34a").set("color","#ffffff");Button cancelar=new Button(new Icon(VaadinIcon.CLOSE_SMALL),e->d.close());cancelar.setTooltipText("Cancelar");cancelar.addThemeVariants(ButtonVariant.LUMO_TERTIARY);cancelar.getStyle().set("background-color","#e2e8f0").set("color","#1e293b");d.add(new FormLayout(codigo,nombre,sucursal,descripcion,asignados));d.getFooter().add(guardar,cancelar);d.open();}
 private void error(Exception e){Notification.show(e.getMessage()==null?"No se pudo completar la operación.":e.getMessage(),5000,Notification.Position.MIDDLE);}
}
