package com.citacloud.app.views;

import com.citacloud.app.models.*;
import com.citacloud.app.security.*;
import com.citacloud.app.services.*;
import com.citacloud.app.views.components.PaginadorTabla;
import com.vaadin.flow.component.*;
import com.vaadin.flow.component.button.*;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.contextmenu.ContextMenu;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.*;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.*;
import com.vaadin.flow.component.textfield.*;
import com.vaadin.flow.data.value.ValueChangeMode;
import com.vaadin.flow.router.*;
import jakarta.annotation.security.PermitAll;
import java.math.*; import java.text.NumberFormat; import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*;

@Route(value="cuentas-por-cobrar",layout=MainLayout.class) @PageTitle("Cuentas por cobrar | CitaCloud") @PermitAll
public class CuentasPorCobrarView extends VerticalLayout {
 private static final DateTimeFormatter FECHA=DateTimeFormatter.ofPattern("dd/MM/yyyy"),FECHA_HORA=DateTimeFormatter.ofPattern("dd/MM/yyyy · hh:mm a",Locale.US); private static final List<String> METODOS=List.of("EFECTIVO","TARJETA","TRANSFERENCIA","CHEQUE","OTRO"),MOTIVOS_REEMBOLSO=List.of("Pago devuelto","Pago duplicado","Error en pago","Cancelación de servicio","Otro"),MOTIVOS_ANULACION=List.of("Pago registrado por error","Pago duplicado","Referencia incorrecta","Otro");
 private final FacturacionService facturacion; private final PagoService pagos; private final UUID empresa; private final Grid<Factura> tabla=new Grid<>(Factura.class,false); private final PaginadorTabla<Factura> paginador=new PaginadorTabla<>(tabla); private final TextField buscar=new TextField(); private final ComboBox<String> estado=new ComboBox<>(); private final DatePicker desde=new DatePicker("Desde"),hasta=new DatePicker("Hasta"); private final Div indicadores=new Div();
 public CuentasPorCobrarView(FacturacionService f,PagoService p){facturacion=f;pagos=p;TenantUserDetails u=AuthService.getAuthenticatedUser();empresa=u==null?null:u.getEmpresaId();setWidthFull();setPadding(true);paginador.setFilasPorPagina(10);cabecera();filtros();tabla();cargar();}
 private void cabecera(){H2 t=new H2("CUENTAS POR COBRAR");t.getStyle().set("margin","0");indicadores.setWidthFull();indicadores.getStyle().set("display","flex").set("gap","1rem").set("flex-wrap","wrap");add(t,new Paragraph("Control y seguimiento de los saldos pendientes generados por facturación."),indicadores);}
 private void filtros(){buscar.setPlaceholder("Paciente, factura o historia clínica");buscar.setClearButtonVisible(true);buscar.setWidth("min(100%,360px)");buscar.setValueChangeMode(ValueChangeMode.LAZY);buscar.setValueChangeTimeout(350);buscar.addValueChangeListener(e->cargar());estado.setItems("Todas","Pendientes","Por vencer","Vencidas","Pagadas");estado.setValue("Todas");estado.setLabel("Estado");estado.addValueChangeListener(e->cargar());desde.addValueChangeListener(e->cargar());hasta.addValueChangeListener(e->cargar());Button limpiar=new Button(VaadinIcon.ERASER.create(),e->{buscar.clear();estado.setValue("Todas");desde.clear();hasta.clear();});limpiar.setTooltipText("Limpiar");limpiar.getStyle().set("background-color","#e2e8f0").set("color","#334155");HorizontalLayout l=new HorizontalLayout(buscar,desde,hasta,estado,limpiar);l.setWidthFull();l.setAlignItems(Alignment.END);l.getStyle().set("flex-wrap","wrap");add(l);}
 private void tabla(){tabla.addColumn(Factura::getNumero).setHeader("FACTURA");tabla.addColumn(f->nombre(f.getPaciente())).setHeader("PACIENTE").setFlexGrow(1);tabla.addColumn(f->fecha(f.getFecha())).setHeader("EMISIÓN");tabla.addColumn(f->dinero(f.getTotal())).setHeader("TOTAL");tabla.addColumn(f->dinero(f.getMontoPagado())).setHeader("PAGADO");tabla.addColumn(f->dinero(f.getSaldo())).setHeader("PENDIENTE");tabla.addColumn(this::estadoFactura).setHeader("ESTADO");tabla.addComponentColumn(f->{Button ver=icono(VaadinIcon.EYE,"Ver detalle",e->detalle(f));Button pagar=icono(VaadinIcon.CREDIT_CARD,"Registrar pago",e->registrarPago(f));pagar.setEnabled(f.getSaldo()!=null&&f.getSaldo().signum()>0);return new HorizontalLayout(ver,pagar);}).setHeader("ACCIONES");tabla.setWidthFull();tabla.setAllRowsVisible(true);add(tabla,paginador);}
 private void cargar(){if(empresa==null){paginador.setItems(List.of());return;}List<Factura> todas=facturacion.listar(empresa);LocalDate hoy=LocalDate.now();paginador.setItems(todas.stream().filter(this::coincide).limit(25).toList());List<Factura> pendientes=todas.stream().filter(f->f.getSaldo()!=null&&f.getSaldo().signum()>0).toList(),vencidas=pendientes.stream().filter(f->f.getFecha()!=null&&f.getFecha().plusDays(30).isBefore(hoy)).toList(),porVencer=pendientes.stream().filter(f->!vencidas.contains(f)).toList();BigDecimal cobrado=pagos.listar(empresa).stream().filter(p->p.getFecha()!=null&&p.getFecha().getMonth()==hoy.getMonth()&&p.getFecha().getYear()==hoy.getYear()&&!"VOIDED".equals(p.getEstado())).map(Pago::getMonto).reduce(BigDecimal.ZERO,BigDecimal::add);indicadores.removeAll();indicadores.add(tarjeta("TOTAL PENDIENTE",dinero(pendientes.stream().map(Factura::getSaldo).reduce(BigDecimal.ZERO,BigDecimal::add))+" · "+pendientes.size()+" cuentas"),tarjeta("POR VENCER",dinero(porVencer.stream().map(Factura::getSaldo).reduce(BigDecimal.ZERO,BigDecimal::add))+" · "+porVencer.size()+" cuentas"),tarjeta("VENCIDO",dinero(vencidas.stream().map(Factura::getSaldo).reduce(BigDecimal.ZERO,BigDecimal::add))+" · "+vencidas.size()+" cuentas"),tarjeta("COBRADO ESTE MES",dinero(cobrado)));}
 private boolean coincide(Factura f){String q=buscar.getValue()==null?"":buscar.getValue().toLowerCase(Locale.ROOT);if(!q.isBlank()&&!(texto(f.getNumero()).toLowerCase(Locale.ROOT).contains(q)||nombre(f.getPaciente()).toLowerCase(Locale.ROOT).contains(q)))return false;if(f.getFecha()!=null&&((desde.getValue()!=null&&f.getFecha().isBefore(desde.getValue()))||(hasta.getValue()!=null&&f.getFecha().isAfter(hasta.getValue()))))return false;return switch(estado.getValue()==null?"Pendientes":estado.getValue()){case "Todas"->true;case "Pagadas"->f.getSaldo()==null||f.getSaldo().signum()==0;default->f.getSaldo()!=null&&f.getSaldo().signum()>0;};}
 private void detalle(Factura f){Dialog d=new Dialog();d.setWidth("min(1100px,96vw)");d.setHeaderTitle("Detalle de cuenta · "+f.getNumero());FormLayout datos=new FormLayout();datos.setResponsiveSteps(new FormLayout.ResponsiveStep("0",1),new FormLayout.ResponsiveStep("600px",2));datos.addFormItem(new Span(nombre(f.getPaciente())),"Paciente");datos.addFormItem(new Span(f.getPaciente()==null?"—":texto(f.getPaciente().getNumeroExpediente())),"Historia clínica");datos.addFormItem(new Span(dinero(f.getTotal())),"Total factura");datos.addFormItem(new Span(dinero(f.getMontoPagado())),"Pagado");datos.addFormItem(new Span(fecha(f.getFecha())),"Emisión");datos.addFormItem(new Span(dinero(f.getSaldo())),"Saldo pendiente");Grid<Pago> historial=new Grid<>(Pago.class,false);historial.addColumn(this::codigo).setHeader("PAGO");historial.addColumn(this::fechaHora).setHeader("FECHA");historial.addColumn(p->texto(p.getMetodoPago())).setHeader("MÉTODO");historial.addColumn(p->dinero(p.getMonto())).setHeader("MONTO");historial.addColumn(p->dinero(pagos.totalReembolsado(empresa,p.getId()))).setHeader("REEMBOLSADO");historial.addColumn(p->estadoPago(p.getEstado())).setHeader("ESTADO");historial.addComponentColumn(p->menu(p,f,d)).setHeader("ACCIONES");historial.setWidthFull();historial.setAllRowsVisible(true);PaginadorTabla<Pago> paginas=new PaginadorTabla<>(historial);paginas.setFilasPorPagina(10);paginas.setItems(pagosFactura(f));VerticalLayout contenido=new VerticalLayout(datos,new H3("Historial de pagos"),new Paragraph("Consulta los pagos aplicados a esta cuenta y administra recibos, reembolsos y anulaciones."),historial,paginas);contenido.setPadding(false);d.add(contenido);d.getFooter().add(cerrar(d));d.open();}
 private Component menu(Pago p,Factura f,Dialog detalle){Button boton=icono(VaadinIcon.ELLIPSIS_DOTS_V,"Acciones",e->{});ContextMenu menu=new ContextMenu(boton);menu.setOpenOnClick(true);menu.getStyle().set("z-index","1000");menu.addItem("Ver recibo",e->recibo(p));var reembolso=menu.addItem("Reembolsar",e->reembolsar(p,f,detalle));reembolso.setEnabled(!"VOIDED".equals(p.getEstado())&&pagos.disponibleReembolso(empresa,p.getId()).signum()>0);var anular=menu.addItem("Anular",e->anular(p,f,detalle));anular.setEnabled("APPLIED".equals(p.getEstado()));return boton;}
 private void recibo(Pago p){getUI().ifPresent(ui->ui.getPage().open("/pagos/"+p.getId()+"/recibo","_blank"));}
 private void reembolsar(Pago p,Factura f,Dialog detalle){BigDecimal disponible=pagos.disponibleReembolso(empresa,p.getId()),ya=pagos.totalReembolsado(empresa,p.getId());Dialog d=new Dialog();d.setHeaderTitle("Reembolsar pago · "+codigo(p));d.setWidth("min(720px,96vw)");BigDecimalField monto=monto("Monto a reembolsar *");monto.setValue(disponible);ComboBox<String> motivo=new ComboBox<>("Motivo *",MOTIVOS_REEMBOLSO),metodo=new ComboBox<>("Método de devolución *",METODOS);metodo.setValue(p.getMetodoPago()==null?"EFECTIVO":p.getMetodoPago());TextField referencia=new TextField("Referencia");TextArea observacion=new TextArea("Observación");FormLayout form=new FormLayout(new Span("Paciente: "+nombre(f.getPaciente())),new Span("Factura: "+f.getNumero()),new Span("Pago original: "+dinero(p.getMonto())),new Span("Reembolsado anteriormente: "+dinero(ya)),new Span("Disponible para reembolsar: "+dinero(disponible)),monto,motivo,metodo,referencia,observacion);form.setResponsiveSteps(new FormLayout.ResponsiveStep("0",1),new FormLayout.ResponsiveStep("600px",2));form.setColspan(observacion,2);Button confirmar=new Button("Confirmar reembolso",e->{try{if(monto.getValue()==null||monto.getValue().signum()<=0||monto.getValue().compareTo(disponible)>0||monto.getValue().scale()>2)throw new IllegalArgumentException("Indique un monto válido que no supere el disponible.");if(motivo.getValue()==null||motivo.getValue().isBlank()||("Otro".equals(motivo.getValue())&&(observacion.getValue()==null||observacion.getValue().isBlank())))throw new IllegalArgumentException("Indique el motivo del reembolso.");confirmar("Confirmar reembolso","Se devolverán "+dinero(monto.getValue())+" del pago "+codigo(p)+".",()->{pagos.reembolsar(empresa,p.getId(),monto.getValue(),metodo.getValue(),referencia.getValue(),motivo.getValue()+" · "+texto(observacion.getValue()));d.close();actualizarDetalle(detalle,f.getId());recibo(p);});}catch(Exception x){aviso(x);}});confirmar.addThemeVariants(ButtonVariant.LUMO_SUCCESS);confirmar.getStyle().set("background-color","#16a34a").set("color","#ffffff");d.add(form);d.getFooter().add(acciones(confirmar,d));d.open();}
 private void anular(Pago p,Factura f,Dialog detalle){Dialog d=new Dialog();d.setHeaderTitle("Anular pago · "+codigo(p));ComboBox<String> motivo=new ComboBox<>("Motivo de anulación *",MOTIVOS_ANULACION);TextArea observacion=new TextArea("Observación *");FormLayout form=new FormLayout(new Span("Paciente: "+nombre(f.getPaciente())),new Span("Factura: "+f.getNumero()),new Span("Monto: "+dinero(p.getMonto())),motivo,observacion);form.setColspan(observacion,2);Button confirmar=new Button("Confirmar anulación",e->{try{if(motivo.getValue()==null||observacion.getValue()==null||observacion.getValue().isBlank())throw new IllegalArgumentException("Indique el motivo y la observación.");confirmar("Confirmar anulación","El pago permanecerá en el historial con estado ANULADO.",()->{pagos.anular(empresa,p.getId(),motivo.getValue()+" · "+observacion.getValue());d.close();actualizarDetalle(detalle,f.getId());recibo(p);});}catch(Exception x){aviso(x);}});confirmar.addThemeVariants(ButtonVariant.LUMO_SUCCESS);confirmar.getStyle().set("background-color","#16a34a").set("color","#ffffff");d.add(form,new Paragraph("El pago permanecerá en el historial con estado ANULADO."));d.getFooter().add(acciones(confirmar,d));d.open();}
 private void confirmar(String titulo,String mensaje,Runnable operacion){Dialog d=new Dialog();d.setHeaderTitle(titulo);d.add(new Paragraph(mensaje));Button ok=new Button(titulo.contains("reembolso")?"Sí, reembolsar":"Sí, anular",e->{try{operacion.run();d.close();Notification.show("Operación registrada correctamente.");}catch(Exception x){aviso(x);}});ok.addThemeVariants(ButtonVariant.LUMO_SUCCESS);ok.getStyle().set("background-color","#16a34a").set("color","#ffffff");d.getFooter().add(acciones(ok,d));d.open();}
 private void actualizarDetalle(Dialog anterior,UUID facturaId){anterior.close();cargar();facturacion.listar(empresa).stream().filter(f->f.getId().equals(facturaId)).findFirst().ifPresent(this::detalle);}
 private void registrarPago(Factura f){Dialog d=new Dialog();d.setHeaderTitle("Registrar pago · "+f.getNumero());BigDecimalField valor=monto("Monto a pagar *");valor.setValue(f.getSaldo());ComboBox<String> metodo=new ComboBox<>("Método de pago *",METODOS);metodo.setValue("EFECTIVO");TextField ref=new TextField("Referencia / autorización");Button ok=new Button(VaadinIcon.DISC.create(),e->{try{CargoFinanciero cargo=pagos.pendientes(empresa,f.getPaciente().getId()).stream().filter(c->c.getFactura()!=null&&c.getFactura().getId().equals(f.getId())).findFirst().orElseThrow(()->new IllegalArgumentException("No existe saldo aplicable."));Pago p=pagos.registrar(empresa,new PagoService.Solicitud(f.getPaciente().getId(),cargo.getSucursal()==null?null:cargo.getSucursal().getId(),metodo.getValue(),valor.getValue(),"EFECTIVO".equals(metodo.getValue())?valor.getValue():null,ref.getValue(),null,null,UUID.randomUUID().toString(),List.of(new PagoService.Aplicacion(cargo.getId(),valor.getValue()))));d.close();cargar();recibo(p);}catch(Exception x){aviso(x);}});ok.setTooltipText("Guardar");ok.addThemeVariants(ButtonVariant.LUMO_SUCCESS);ok.getStyle().set("background-color","#16a34a").set("color","#ffffff");d.add(new FormLayout(valor,metodo,ref));d.getFooter().add(acciones(ok,d));d.open();}
 private List<Pago> pagosFactura(Factura f){return pagos.listar(empresa).stream().filter(p->p.getFactura()!=null&&p.getFactura().getId().equals(f.getId())||pagos.aplicaciones(empresa,p.getId()).stream().anyMatch(a->a.getCargo()!=null&&a.getCargo().getFactura()!=null&&a.getCargo().getFactura().getId().equals(f.getId()))).toList();}
 private Button icono(VaadinIcon i,String tip,ComponentEventListener<ClickEvent<Button>> accion){Button b=new Button(i.create(),accion);b.setTooltipText(tip);b.addThemeVariants(ButtonVariant.LUMO_TERTIARY_INLINE);b.getStyle().set("background","transparent").set("border","none").set("box-shadow","none").set("min-width","auto").set("padding","0");return b;}
 private HorizontalLayout acciones(Button ok,Dialog d){Button cancelar=new Button(VaadinIcon.CLOSE.create(),e->d.close());cancelar.setTooltipText("Cancelar");cancelar.getStyle().set("background-color","#e2e8f0").set("color","#334155");HorizontalLayout h=new HorizontalLayout(ok,cancelar);h.setWidthFull();h.setJustifyContentMode(FlexComponent.JustifyContentMode.END);return h;} private Button cerrar(Dialog d){Button b=new Button(VaadinIcon.CLOSE.create(),e->d.close());b.setTooltipText("Cerrar");b.getStyle().set("background-color","#e2e8f0").set("color","#334155");return b;} private Component tarjeta(String t,String v){Div d=new Div(new Span(t),new H3(v));d.getStyle().set("flex","1 1 220px").set("padding",".75rem 1rem").set("background","var(--lumo-contrast-5pct)").set("border-radius","var(--lumo-border-radius-l)");return d;} private BigDecimalField monto(String etiqueta){BigDecimalField b=new BigDecimalField(etiqueta);b.setPrefixComponent(new Span("RD$"));return b;} private String nombre(Paciente p){return p==null?"—":texto(p.getNombreCompleto());} private String estadoFactura(Factura f){return f.getSaldo()==null||f.getSaldo().signum()==0?"PAGADA":f.getMontoPagado()!=null&&f.getMontoPagado().signum()>0?"PARCIAL":"PENDIENTE";} private String estadoPago(String v){return switch(v==null?"APPLIED":v){case "APPLIED"->"APLICADO";case "PARTIALLY_REFUNDED"->"PARCIALMENTE REEMBOLSADO";case "REFUNDED"->"REEMBOLSADO";case "VOIDED"->"ANULADO";default->v;};} private String fecha(LocalDate v){return v==null?"—":v.format(FECHA);} private String fechaHora(Pago p){return p.getCreadoEn()==null?fecha(p.getFecha()):p.getCreadoEn().format(FECHA_HORA);} private String codigo(Pago p){return p.getNumero()==null?"PAG-"+p.getId().toString().substring(0,8).toUpperCase(Locale.ROOT):p.getNumero();} private String texto(String v){return v==null||v.isBlank()?"—":v;} private String dinero(BigDecimal v){NumberFormat n=NumberFormat.getNumberInstance(Locale.US);n.setMinimumFractionDigits(2);n.setMaximumFractionDigits(2);return "RD$ "+n.format(v==null?BigDecimal.ZERO:v);} private void aviso(Exception e){Notification.show(e.getMessage()==null?"No se pudo completar la operación.":e.getMessage(),5000,Notification.Position.MIDDLE);}
}
