package com.citacloud.app.views;

import com.citacloud.app.models.*;
import com.citacloud.app.repositories.PacienteRepository;
import com.citacloud.app.security.*;
import com.citacloud.app.services.LaboratorioService;
import com.citacloud.app.views.components.PaginadorTabla;
import com.vaadin.flow.component.*;
import com.vaadin.flow.component.button.*;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.*;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.*;
import com.vaadin.flow.component.textfield.*;
import com.vaadin.flow.data.value.ValueChangeMode;
import com.vaadin.flow.router.*;
import jakarta.annotation.security.PermitAll;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.util.*;

@Route(value="laboratorio",layout=MainLayout.class) @PageTitle("Laboratorio | CitaCloud") @PermitAll
public class LaboratorioView extends VerticalLayout {
 private final LaboratorioService service; private final PacienteRepository pacientes; private final UUID empresa;
 private final Grid<OrdenEstudio> ordenes=new Grid<>(OrdenEstudio.class,false); private final PaginadorTabla<OrdenEstudio> paginas=new PaginadorTabla<>(ordenes); private final TextField buscar=new TextField("Buscar"); private final ComboBox<String> estado=new ComboBox<>("Estado");
 public LaboratorioView(LaboratorioService s,PacienteRepository p){service=s;pacientes=p;TenantUserDetails u=AuthService.getAuthenticatedUser();empresa=u==null?null:u.getEmpresaId();setWidthFull();setPadding(true);setSpacing(true);paginas.setFilasPorPagina(10);construir();estado.setItems("","PENDIENTE","EN_PROCESO","COMPLETADA");estado.setItemLabelGenerator(this::estadoTexto);cargar();}
 private void construir(){add(new H2("Laboratorio"),new Paragraph("Recepción de órdenes, muestras, resultados y validación."),indicadores());buscar.setPlaceholder("Paciente, orden o estudio");buscar.setValueChangeMode(ValueChangeMode.LAZY);buscar.addValueChangeListener(e->cargar());estado.setItems("","PENDIENTE","EN_PROCESO","POR_VALIDAR","COMPLETADA");estado.setPlaceholder("Todos");estado.addValueChangeListener(e->cargar());HorizontalLayout filtros=new HorizontalLayout(buscar,estado);filtros.setWidthFull();filtros.setFlexGrow(1,buscar);add(filtros);ordenes.addColumn(OrdenEstudio::getNumero).setHeader("ORDEN");ordenes.addColumn(this::paciente).setHeader("PACIENTE").setFlexGrow(1);ordenes.addColumn(o->fecha(o.getEmitidoEn())).setHeader("FECHA");ordenes.addColumn(o->service.estudios(empresa,o.getId()).size()).setHeader("ESTUDIOS");ordenes.addComponentColumn(o->badge(service.estadoOrden(empresa,o))).setHeader("ESTADO");ordenes.addComponentColumn(o->icono(VaadinIcon.EYE,"Ver orden",e->detalle(o))).setHeader("ACCIONES");ordenes.setWidthFull();ordenes.setAllRowsVisible(true);add(ordenes,paginas);}
 private Component indicadores(){LaboratorioService.Resumen r=empresa==null?new LaboratorioService.Resumen(0,0,0,0):service.resumen(empresa);HorizontalLayout h=new HorizontalLayout(card("PENDIENTES",r.pendientes()),card("MUESTRAS",r.muestras()),card("EN PROCESO",r.enProceso()));h.setWidthFull();h.getStyle().set("flex-wrap","wrap");return h;} private Component card(String t,long n){Div d=new Div(new Span(t),new H3(String.valueOf(n)));d.getStyle().set("flex","1 1 180px").set("padding","1rem").set("border-radius","10px").set("background","var(--lumo-contrast-5pct)");return d;}
 private void cargar(){if(empresa!=null)paginas.setItems(service.ordenes(empresa,buscar.getValue(),estado.getValue()));}
private void detalle(OrdenEstudio orden){Dialog d=new Dialog();d.setHeaderTitle("Orden "+valor(orden.getNumero()));d.setWidth("min(1150px,96vw)");FormLayout cabecera=new FormLayout(dato("Paciente",paciente(orden)),dato("Historia clínica",historia(orden)),dato("Fecha",fecha(orden.getEmitidoEn())),dato("Estado",estadoTexto(service.estadoOrden(empresa,orden))),dato("Prioridad",valor(orden.getPrioridad())),dato("Observación",valor(orden.getObservaciones())));cabecera.setResponsiveSteps(new FormLayout.ResponsiveStep("0",1),new FormLayout.ResponsiveStep("760px",3));Grid<DetalleOrdenEstudio> estudios=new Grid<>(DetalleOrdenEstudio.class,false);estudios.addColumn(DetalleOrdenEstudio::getEstudio).setHeader("ESTUDIO").setFlexGrow(1);estudios.addColumn(DetalleOrdenEstudio::getTipo).setHeader("TIPO");estudios.addComponentColumn(x->badge(x.getEstado())).setHeader("ESTADO");estudios.addComponentColumn(x->icono(VaadinIcon.EDIT,"Registrar resultado",e->formResultado(d,orden,x,null))).setHeader("ACCIONES");estudios.setItems(service.estudios(empresa,orden.getId()));estudios.setAllRowsVisible(true);Grid<MuestraLaboratorio> muestras=tablaMuestras(d,orden);Grid<ResultadoLaboratorio> resultados=tablaResultados(d,orden);Button nuevaMuestra=icono(VaadinIcon.PLUS,"Registrar muestra",e->formMuestra(d,orden));d.add(cabecera,new HorizontalLayout(new H4("MUESTRAS"),nuevaMuestra),muestras,new H4("ESTUDIOS SOLICITADOS"),estudios,new H4("RESULTADOS E HISTORIAL"),resultados);d.getFooter().add(cerrar(d));d.open();}
 private Grid<MuestraLaboratorio> tablaMuestras(Dialog padre,OrdenEstudio orden){Grid<MuestraLaboratorio> g=new Grid<>(MuestraLaboratorio.class,false);g.addColumn(MuestraLaboratorio::getCodigo).setHeader("CÓDIGO");g.addColumn(MuestraLaboratorio::getTipoMuestra).setHeader("MUESTRA");g.addColumn(x->fecha(x.getTomadaEn())).setHeader("RECEPCIÓN");g.addComponentColumn(x->badge(x.getEstado())).setHeader("ESTADO");g.addComponentColumn(x->"RECIBIDA".equals(x.getEstado())?icono(VaadinIcon.BAN,"Rechazar muestra",e->rechazarMuestra(padre,orden,x)):new Span()).setHeader("ACCIONES");g.setItems(service.muestras(empresa,orden.getId()));g.setAllRowsVisible(true);return g;}
private Grid<ResultadoLaboratorio> tablaResultados(Dialog padre,OrdenEstudio orden){Grid<ResultadoLaboratorio> g=new Grid<>(ResultadoLaboratorio.class,false);g.addColumn(r->service.estudios(empresa,orden.getId()).stream().filter(x->x.getId().equals(r.getDetalleOrdenId())).map(DetalleOrdenEstudio::getEstudio).findFirst().orElse("—")).setHeader("ESTUDIO").setFlexGrow(1);g.addColumn(r->r.getResultadoNumerico()==null?valor(r.getResultado()):r.getResultadoNumerico().stripTrailingZeros().toPlainString()).setHeader("RESULTADO");g.addColumn(r->valor(r.getUnidad())).setHeader("UNIDAD");g.addColumn(r->valor(r.getIndicador())).setHeader("INDICADOR");g.addComponentColumn(r->badge(r.getEstado())).setHeader("ESTADO");g.addColumn(r->"v"+r.getVersion()).setHeader("VERSIÓN");g.addComponentColumn(r->{HorizontalLayout h=new HorizontalLayout();if(!"COMPLETADA".equals(r.getEstado()))h.add(icono(VaadinIcon.CHECK,"Completar",e->completar(padre,orden,r)));return h;}).setHeader("ACCIONES");g.setItems(service.resultados(empresa,orden.getId()));g.setAllRowsVisible(true);return g;}
 private void formMuestra(Dialog padre,OrdenEstudio orden){Dialog d=new Dialog();d.setHeaderTitle("Registrar muestra");TextField tipo=new TextField("Tipo de muestra *");TextArea observacion=new TextArea("Observación");Button guardar=guardar("Guardar muestra",e->{try{service.registrarMuestra(empresa,orden.getId(),tipo.getValue(),observacion.getValue());refrescar(d,padre,orden);}catch(Exception x){aviso(x);}});d.add(new FormLayout(tipo,observacion));d.getFooter().add(guardar,cerrar(d));d.open();}
 private void rechazarMuestra(Dialog padre,OrdenEstudio orden,MuestraLaboratorio muestra){Dialog d=new Dialog();d.setHeaderTitle("Rechazar muestra "+muestra.getCodigo());TextArea motivo=new TextArea("Motivo de rechazo *");Button guardar=guardar("Confirmar rechazo",e->{try{service.rechazarMuestra(empresa,muestra.getId(),motivo.getValue());refrescar(d,padre,orden);}catch(Exception x){aviso(x);}});d.add(motivo);d.getFooter().add(guardar,cerrar(d));d.open();}
private void formResultado(Dialog padre,OrdenEstudio orden,DetalleOrdenEstudio detalle,ResultadoLaboratorio anterior){ResultadoLaboratorio encontrado=anterior;if(encontrado==null&&detalle!=null)encontrado=service.resultados(empresa,orden.getId()).stream().filter(r->r.getDetalleOrdenId().equals(detalle.getId())).findFirst().orElse(null);final ResultadoLaboratorio actual=encontrado;Dialog d=new Dialog();d.setHeaderTitle(actual==null?"Registrar resultado":"VALIDADO".equals(actual.getEstado())?"Corregir resultado":"Editar resultado");ComboBox<MuestraLaboratorio> muestra=new ComboBox<>("Muestra");muestra.setItems(service.muestras(empresa,orden.getId()).stream().filter(m->!"RECHAZADA".equals(m.getEstado())).toList());muestra.setItemLabelGenerator(m->m.getCodigo()+" · "+m.getTipoMuestra());TextArea texto=new TextArea("Resultado textual");BigDecimalField numero=new BigDecimalField("Resultado numérico"),minimo=new BigDecimalField("Referencia mínima"),maximo=new BigDecimalField("Referencia máxima");TextField unidad=new TextField("Unidad");TextArea observacion=new TextArea("Observación");TextArea motivo=new TextArea("Motivo de corrección *");if(actual!=null){muestra.setValue(service.muestras(empresa,orden.getId()).stream().filter(m->m.getId().equals(actual.getMuestraId())).findFirst().orElse(null));texto.setValue(actual.getResultado()==null?"":actual.getResultado());numero.setValue(actual.getResultadoNumerico());minimo.setValue(actual.getReferenciaMinima());maximo.setValue(actual.getReferenciaMaxima());unidad.setValue(actual.getUnidad()==null?"":actual.getUnidad());observacion.setValue(actual.getObservacion()==null?"":actual.getObservacion());}FormLayout f=new FormLayout(muestra,texto,numero,unidad,minimo,maximo,observacion);f.setResponsiveSteps(new FormLayout.ResponsiveStep("0",1),new FormLayout.ResponsiveStep("760px",3));f.setColspan(texto,3);f.setColspan(observacion,3);if(actual!=null&&"VALIDADO".equals(actual.getEstado())){f.add(motivo);f.setColspan(motivo,3);}Button borrador=guardar("Guardar borrador",e->guardarResultado(d,padre,orden,detalle,actual,muestra,texto,numero,unidad,minimo,maximo,observacion,motivo,false));d.add(f);d.getFooter().add(borrador,cerrar(d));d.open();}
private void guardarResultado(Dialog d,Dialog padre,OrdenEstudio orden,DetalleOrdenEstudio detalle,ResultadoLaboratorio anterior,ComboBox<MuestraLaboratorio> muestra,TextArea texto,BigDecimalField numero,TextField unidad,BigDecimalField minimo,BigDecimalField maximo,TextArea observacion,TextArea motivo,boolean enviar){try{UUID estudio=detalle==null?anterior.getDetalleOrdenId():detalle.getId();LaboratorioService.RegistroResultado r=new LaboratorioService.RegistroResultado(estudio,muestra.getValue()==null?null:muestra.getValue().getId(),texto.getValue(),numero.getValue(),unidad.getValue(),minimo.getValue(),maximo.getValue(),observacion.getValue());if(anterior==null||!"VALIDADO".equals(anterior.getEstado()))service.guardarResultado(empresa,r,enviar);else{service.corregir(empresa,anterior.getId(),r,motivo.getValue());if(enviar)service.guardarResultado(empresa,r,true);}refrescar(d,padre,orden);}catch(Exception x){aviso(x);}}
private void completar(Dialog padre,OrdenEstudio orden,ResultadoLaboratorio r){try{service.completar(empresa,r.getId());padre.close();detalle(orden);cargar();}catch(Exception x){aviso(x);}}
 private void refrescar(Dialog hijo,Dialog padre,OrdenEstudio orden){hijo.close();padre.close();detalle(orden);cargar();}
private String paciente(OrdenEstudio o){return pacientes.findByIdAndEmpresaId(o.getPacienteId(),empresa).map(Paciente::getNombreCompleto).orElse("—");}private String historia(OrdenEstudio o){return pacientes.findByIdAndEmpresaId(o.getPacienteId(),empresa).map(Paciente::getNumeroExpediente).orElse("—");}private Component dato(String e,String v){return new Div(new Span(e),new Paragraph(valor(v)));}private String valor(String v){return v==null||v.isBlank()?"—":v;}private String fecha(java.time.LocalDateTime f){return f==null?"—":f.format(DateTimeFormatter.ofPattern("dd/MM/yyyy hh:mm a"));}private Span badge(String e){Span s=new Span(estadoTexto(e));s.getStyle().set("font-weight","600").set("font-size",".78rem");return s;}private String estadoTexto(String e){return e==null?"—":e.replace('_',' ');}private Button icono(VaadinIcon i,String t,ComponentEventListener<ClickEvent<Button>> l){Button b=new Button(i.create(),l);b.setTooltipText(t);b.addThemeVariants(ButtonVariant.LUMO_TERTIARY_INLINE);return b;}private Button guardar(String t,ComponentEventListener<ClickEvent<Button>> l){Button b=new Button(t.startsWith("Enviar")?VaadinIcon.CLIPBOARD_CHECK.create():VaadinIcon.DISC.create(),l);b.setTooltipText(t);b.addThemeVariants(ButtonVariant.LUMO_SUCCESS);b.getStyle().set("background-color","#16a34a").set("color","#ffffff");return b;}private Button cerrar(Dialog d){Button b=new Button(VaadinIcon.CLOSE.create(),e->d.close());b.setTooltipText("Cancelar");b.getStyle().set("background-color","#e2e8f0").set("color","#000000");return b;}private void aviso(Exception x){Notification.show(x.getMessage()==null?"No se pudo completar la operación.":x.getMessage(),5000,Notification.Position.MIDDLE);}
}
