package com.citacloud.app.views;

import com.citacloud.app.models.Sucursal;
import com.citacloud.app.security.AuthService;
import com.citacloud.app.services.ReportesFinancierosService;
import com.citacloud.app.services.ReportesFinancierosExportService;
import com.citacloud.app.services.SucursalService;
import com.citacloud.app.views.components.PaginadorTabla;
import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.*;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.*;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.server.StreamResource;
import jakarta.annotation.security.PermitAll;
import java.io.ByteArrayInputStream; import java.math.BigDecimal; import java.text.NumberFormat; import java.time.LocalDate; import java.util.*;

@Route(value = "reportes-financieros", layout = MainLayout.class)
@PageTitle("Reportes financieros | CitaCloud")
@PermitAll
public class ReportesFinancierosView extends VerticalLayout {
 private final ReportesFinancierosService reportes; private final ReportesFinancierosExportService exportador; private final UUID empresa; private final ComboBox<String> periodo=new ComboBox<>("Período"); private final ComboBox<Sucursal> sucursal=new ComboBox<>("Sucursal"); private final DatePicker desde=new DatePicker("Desde"),hasta=new DatePicker("Hasta"); private final Div cuerpo=new Div();
 public ReportesFinancierosView(ReportesFinancierosService r,ReportesFinancierosExportService ex,SucursalService ss){reportes=r;exportador=ex;var u=AuthService.getAuthenticatedUser();empresa=u==null?null:u.getEmpresaId();setWidthFull();setPadding(true);add(new H2("Reportes financieros"),new Paragraph("Análisis financiero y operativo. Solo consulta; no modifica transacciones."));periodo.setItems("Hoy","Esta semana","Este mes","Últimos 30 días","Este trimestre","Este año","Personalizado");periodo.setValue("Este mes");periodo.addValueChangeListener(e->{boolean personalizado="Personalizado".equals(e.getValue());desde.setVisible(personalizado);hasta.setVisible(personalizado);if(!personalizado)cargar();});sucursal.setItems(empresa==null?List.of():ss.listarActivas(empresa));sucursal.setItemLabelGenerator(Sucursal::getNombre);sucursal.setPlaceholder("Todas las sucursales");sucursal.setClearButtonVisible(true);sucursal.addValueChangeListener(e->cargar());desde.setVisible(false);hasta.setVisible(false);desde.addValueChangeListener(e->cargar());hasta.addValueChangeListener(e->cargar());HorizontalLayout campos=new HorizontalLayout(periodo,sucursal,desde,hasta);HorizontalLayout acciones=new HorizontalLayout(enlacePdf(),enlaceExcel());HorizontalLayout filtros=new HorizontalLayout(campos,acciones);filtros.setWidthFull();filtros.setAlignItems(Alignment.END);filtros.setJustifyContentMode(JustifyContentMode.BETWEEN);filtros.getStyle().set("flex-wrap","wrap");cuerpo.setWidthFull();add(filtros,cuerpo);cargar();}
 private void cargar(){if(empresa==null)return;try{var f=filtro();var r=reportes.resumen(empresa,f);cuerpo.removeAll();HorizontalLayout cards=new HorizontalLayout(card("FACTURADO",dinero(r.facturado()),r.facturas()+" facturas"),card("COBRADO",dinero(r.cobrado()),r.pagos()+" pagos"),card("POR COBRAR",dinero(r.porCobrar()),r.cuentas()+" cuentas"),card("REEMBOLSADO",dinero(r.reembolsado()),r.reembolsos()+" operaciones"));cards.setWidthFull();cards.getStyle().set("flex-wrap","wrap");cuerpo.add(cards,grafica(reportes.serieTemporal(empresa,f)),tablaFacturas(f),tablaPagos(f),tablaCuentas(f),tablaCaja(f),tablaReembolsos(f),tablaServicios(f));}catch(IllegalArgumentException e){Notification.show(e.getMessage());}}
 private Component reportes(){HorizontalLayout h=new HorizontalLayout(enlace("Facturación",VaadinIcon.INVOICE,"/facturacion"),enlace("Cobros y pagos",VaadinIcon.CREDIT_CARD,"/pagos"),enlace("Cuentas por cobrar",VaadinIcon.DOLLAR,"/cuentas-por-cobrar"),enlace("Caja",VaadinIcon.CASH,"/caja"),enlace("Servicios",VaadinIcon.CLIPBOARD_TEXT,"/servicios"));h.setWidthFull();h.getStyle().set("flex-wrap","wrap");return h;}
 private Component tablaFacturas(ReportesFinancierosService.Filtro f){Grid<com.citacloud.app.models.Factura> g=new Grid<>(com.citacloud.app.models.Factura.class,false);g.addColumn(com.citacloud.app.models.Factura::getNumero).setHeader("FACTURA");g.addColumn(x->x.getFecha()).setHeader("FECHA");g.addColumn(x->x.getPaciente()==null?"—":x.getPaciente().getNombreCompleto()).setHeader("PACIENTE");g.addColumn(x->dinero(x.getTotal())).setHeader("TOTAL");g.addColumn(com.citacloud.app.models.Factura::getEstado).setHeader("ESTADO");return seccion("Facturación",g,reportes.facturas(empresa,f));}
 private Component tablaPagos(ReportesFinancierosService.Filtro f){Grid<com.citacloud.app.models.Pago> g=new Grid<>(com.citacloud.app.models.Pago.class,false);g.addColumn(com.citacloud.app.models.Pago::getNumero).setHeader("PAGO");g.addColumn(com.citacloud.app.models.Pago::getFecha).setHeader("FECHA");g.addColumn(com.citacloud.app.models.Pago::getMetodoPago).setHeader("MÉTODO");g.addColumn(x->dinero(x.getMonto())).setHeader("MONTO");return seccion("Cobros y pagos",g,reportes.pagos(empresa,f));}
 private Component tablaCuentas(ReportesFinancierosService.Filtro f){Grid<com.citacloud.app.models.CargoFinanciero> g=new Grid<>(com.citacloud.app.models.CargoFinanciero.class,false);g.addColumn(com.citacloud.app.models.CargoFinanciero::getReferenciaOrigen).setHeader("FACTURA");g.addColumn(x->x.getPaciente()==null?"—":x.getPaciente().getNombreCompleto()).setHeader("PACIENTE");g.addColumn(com.citacloud.app.models.CargoFinanciero::getFecha).setHeader("FECHA");g.addColumn(x->dinero(x.getSaldo())).setHeader("PENDIENTE");g.addColumn(com.citacloud.app.models.CargoFinanciero::getEstado).setHeader("ESTADO");return seccion("Cuentas por cobrar",g,reportes.cuentas(empresa,f));}
 private Component tablaCaja(ReportesFinancierosService.Filtro f){Grid<ReportesFinancierosService.CajaResumen> g=new Grid<>(ReportesFinancierosService.CajaResumen.class,false);g.addColumn(ReportesFinancierosService.CajaResumen::caja).setHeader("CAJA");g.addColumn(ReportesFinancierosService.CajaResumen::aperturas).setHeader("APERTURAS");g.addColumn(x->dinero(x.ingresos())).setHeader("INGRESOS");g.addColumn(x->dinero(x.egresos())).setHeader("EGRESOS");g.addColumn(x->dinero(x.diferencia())).setHeader("DIFERENCIA");return seccion("Caja",g,reportes.cajas(empresa,f));}
 private Component tablaReembolsos(ReportesFinancierosService.Filtro f){Grid<com.citacloud.app.models.ReembolsoPago> g=new Grid<>(com.citacloud.app.models.ReembolsoPago.class,false);g.addColumn(x->x.getReembolsadoEn()==null?"—":x.getReembolsadoEn().toLocalDate()).setHeader("FECHA");g.addColumn(com.citacloud.app.models.ReembolsoPago::getMetodoPago).setHeader("MÉTODO");g.addColumn(x->dinero(x.getMonto())).setHeader("MONTO");g.addColumn(com.citacloud.app.models.ReembolsoPago::getMotivo).setHeader("MOTIVO");return seccion("Reembolsos",g,reportes.reembolsos(empresa,f));}
 private Component tablaServicios(ReportesFinancierosService.Filtro f){Grid<ReportesFinancierosService.ServicioFacturado> g=new Grid<>(ReportesFinancierosService.ServicioFacturado.class,false);g.addColumn(ReportesFinancierosService.ServicioFacturado::nombre).setHeader("SERVICIO");g.addColumn(x->x.cantidad()).setHeader("CANTIDAD");g.addColumn(x->dinero(x.facturado())).setHeader("FACTURADO");g.addColumn(x->x.porcentaje()+"%").setHeader("% TOTAL");return seccion("Servicios",g,reportes.servicios(empresa,f));}
 private <T> Component seccion(String titulo,Grid<T> tabla,Collection<T> datos){tabla.setWidthFull();tabla.setAllRowsVisible(true);PaginadorTabla<T> p=new PaginadorTabla<>(tabla);p.setFilasPorPagina(10);p.setItems(datos);VerticalLayout v=new VerticalLayout(new H3(titulo),tabla,p);v.setPadding(false);return v;}
 private Button enlace(String texto,VaadinIcon icono,String ruta){Button b=new Button(texto,icono.create(),e->getUI().ifPresent(ui->ui.navigate(ruta)));b.setTooltipText("Ver reporte de "+texto);b.getStyle().set("min-height","72px").set("flex","1 1 180px");return b;}
 private Anchor enlacePdf(){StreamResource recurso=new StreamResource("Reporte_Financiero.pdf",()->{var f=filtro();var r=reportes.resumen(empresa,f);String s=sucursal.getValue()==null?"Todas las sucursales":sucursal.getValue().getNombre();return new ByteArrayInputStream(exportador.pdf(r,f,s,reportes.facturas(empresa,f),reportes.pagos(empresa,f),reportes.reembolsos(empresa,f)));});Anchor a=new Anchor(recurso,"");a.setTarget("_blank");Button b=new Button("Exportar PDF",VaadinIcon.DOWNLOAD.create());b.setTooltipText("Exportar PDF");b.getStyle().set("background-color","#1f6feb").set("color","#ffffff").set("height","40px").set("padding","0 1rem");a.add(b);return a;}
 private Anchor enlaceExcel(){StreamResource recurso=new StreamResource("Reporte_Financiero.xlsx",()->{var f=filtro();var r=reportes.resumen(empresa,f);String s=sucursal.getValue()==null?"Todas las sucursales":sucursal.getValue().getNombre();return new ByteArrayInputStream(exportador.excel(r,f,s,reportes.facturas(empresa,f),reportes.pagos(empresa,f),reportes.reembolsos(empresa,f)));});Anchor a=new Anchor(recurso,"");a.getElement().setAttribute("download",true);Button b=new Button("Exportar Excel",VaadinIcon.TABLE.create());b.setTooltipText("Exportar Excel");b.getStyle().set("background-color","#e2e8f0").set("color","#334155").set("height","40px").set("padding","0 1rem");a.add(b);return a;}
 private Component grafica(List<ReportesFinancierosService.SerieTemporal> serie){BigDecimal totalFacturado=serie.stream().map(ReportesFinancierosService.SerieTemporal::facturado).reduce(BigDecimal.ZERO,BigDecimal::add),totalCobrado=serie.stream().map(ReportesFinancierosService.SerieTemporal::cobrado).reduce(BigDecimal.ZERO,BigDecimal::add),max=totalFacturado.max(totalCobrado);VerticalLayout caja=new VerticalLayout(new H3("Facturado vs cobrado"));caja.setPadding(true);caja.getStyle().set("background","var(--lumo-contrast-5pct)").set("border-radius","var(--lumo-border-radius-l)");HorizontalLayout comparacion=new HorizontalLayout(new Span("Facturado"),barra(totalFacturado,max,"#2563eb"),new Span("Cobrado"),barra(totalCobrado,max,"#16a34a"));comparacion.setWidthFull();comparacion.setAlignItems(Alignment.CENTER);comparacion.getStyle().set("gap",".6rem");caja.add(comparacion,new Span("Azul: "+dinero(totalFacturado)+" · Verde: "+dinero(totalCobrado)));return caja;}
 private Div barra(BigDecimal valor,BigDecimal max,String color){Div b=new Div(new Span(dinero(valor)));int ancho=max.signum()==0?0:valor.multiply(BigDecimal.valueOf(100)).divide(max,0,java.math.RoundingMode.HALF_UP).intValue();b.getStyle().set("width",Math.max(4,ancho)+"%").set("min-width","4rem").set("padding",".25rem .5rem").set("background",color).set("color","white").set("border-radius","4px");return b;}
 private void exportarFormato(boolean pdf){try{var f=filtro();var r=reportes.resumen(empresa,f);String s=sucursal.getValue()==null?"Todas las sucursales":sucursal.getValue().getNombre();Dialog d=new Dialog();d.setHeaderTitle(pdf?"Exportar PDF":"Exportar Excel");StreamResource recurso=pdf?new StreamResource("Reporte_Financiero_"+f.hasta()+".pdf",()->new ByteArrayInputStream(exportador.pdf(r,f,s,reportes.facturas(empresa,f),reportes.pagos(empresa,f),reportes.reembolsos(empresa,f)))):new StreamResource("Reporte_Financiero_"+f.hasta()+".xlsx",()->new ByteArrayInputStream(exportador.excel(r,f,s)));Anchor abrir=new Anchor(recurso,pdf?"Abrir PDF":"Descargar Excel");if(pdf)abrir.setTarget("_blank");else abrir.getElement().setAttribute("download",true);d.add(new Paragraph("Período: "+f.desde()+" - "+f.hasta()),abrir);d.getFooter().add(icono(VaadinIcon.CLOSE_SMALL,"Cerrar",e->d.close()));d.open();}catch(IllegalArgumentException e){Notification.show(e.getMessage());}}
 private void exportar(){try{var f=filtro();var r=reportes.resumen(empresa,f);String s=sucursal.getValue()==null?"Todas las sucursales":sucursal.getValue().getNombre();Dialog d=new Dialog();d.setHeaderTitle("Exportar reporte");Anchor pdf=new Anchor(new StreamResource("Reporte_Financiero_"+f.hasta()+".pdf",()->new ByteArrayInputStream(exportador.pdf(r,f,s,reportes.facturas(empresa,f),reportes.pagos(empresa,f),reportes.reembolsos(empresa,f)))),"PDF");pdf.setTarget("_blank");Anchor excel=new Anchor(new StreamResource("reportes-financieros.xlsx",()->new ByteArrayInputStream(exportador.excel(r,f,s))),"Excel");excel.getElement().setAttribute("download",true);d.add(new Paragraph("Período: "+f.desde()+" - "+f.hasta()),new Paragraph("Sucursal: "+s));d.getFooter().add(pdf,excel,icono(VaadinIcon.CLOSE_SMALL,"Cerrar",e->d.close()));d.open();}catch(IllegalArgumentException e){Notification.show(e.getMessage());}}
 private ReportesFinancierosService.Filtro filtro(){LocalDate h=LocalDate.now(),d;switch(periodo.getValue()){case "Hoy"->d=h;case "Esta semana"->d=h.minusDays(h.getDayOfWeek().getValue()-1);case "Últimos 30 días"->d=h.minusDays(29);case "Este trimestre"->d=h.withMonth(((h.getMonthValue()-1)/3)*3+1).withDayOfMonth(1);case "Este año"->d=h.withDayOfYear(1);case "Personalizado"->{d=desde.getValue();h=hasta.getValue();}default->d=h.withDayOfMonth(1);}return new ReportesFinancierosService.Filtro(d,h,sucursal.getValue()==null?null:sucursal.getValue().getId());}
 private Div card(String t,String v,String s){Div d=new Div(new Span(t),new H3(v),new Span(s));d.getStyle().set("padding","1rem").set("background","var(--lumo-contrast-5pct)").set("border-radius","var(--lumo-border-radius-l)").set("flex","1 1 180px");return d;} private Button icono(VaadinIcon i,String t,com.vaadin.flow.component.ComponentEventListener<com.vaadin.flow.component.ClickEvent<Button>> e){Button b=new Button(i.create(),e);b.setTooltipText(t);return b;} private String dinero(BigDecimal x){return "RD$ "+NumberFormat.getNumberInstance(Locale.US).format(x==null?BigDecimal.ZERO:x.setScale(2));}
}
