package com.citacloud.app.controllers;
import com.citacloud.app.exceptions.UnauthorizedException; import com.citacloud.app.models.*; import com.citacloud.app.security.*; import com.citacloud.app.services.CajaService; import jakarta.annotation.security.PermitAll; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.math.BigDecimal; import java.util.*;
@RestController @RequestMapping("/api/cash") @PermitAll public class CajaController {
 private final CajaService caja; public CajaController(CajaService caja){this.caja=caja;} private TenantUserDetails usuario(){TenantUserDetails u=AuthService.getAuthenticatedUser();if(u==null)throw new UnauthorizedException();return u;}
 public record Apertura(UUID sucursalId,UUID cajaId,BigDecimal fondoInicial,String nota,String claveIdempotencia){} public record Movimiento(BigDecimal monto,String metodo,String concepto,String nota,String claveIdempotencia){} public record Cierre(BigDecimal efectivoContado,String nota,String motivoDiferencia,String claveIdempotencia){}
 @GetMapping("/registers") public ResponseEntity<List<Caja>> cajas(){TenantUserDetails u=usuario();return ResponseEntity.ok(caja.cajas(u.getEmpresaId()));}
 @GetMapping("/authorized") public ResponseEntity<List<Caja>> autorizadas(@RequestParam UUID sucursalId){TenantUserDetails u=usuario();return ResponseEntity.ok(caja.autorizadas(u.getEmpresaId(),sucursalId));}
 @GetMapping("/current") public ResponseEntity<?> actual(@RequestParam UUID sucursalId){TenantUserDetails u=usuario();return ResponseEntity.ok(caja.actual(u.getEmpresaId(),sucursalId).map(s->caja.resumen(u.getEmpresaId(),s.getId())).orElse(null));}
 @PostMapping("/open") public ResponseEntity<SesionCaja> abrir(@RequestBody Apertura r){TenantUserDetails u=usuario();return ResponseEntity.ok(caja.abrirEnCaja(u.getEmpresaId(),r.sucursalId(),r.cajaId(),r.fondoInicial(),r.nota(),r.claveIdempotencia()));}
 @GetMapping("/{id}") public ResponseEntity<CajaService.Resumen> detalle(@PathVariable UUID id){TenantUserDetails u=usuario();return ResponseEntity.ok(caja.resumen(u.getEmpresaId(),id));}
 @GetMapping("/{id}/movements") public ResponseEntity<List<MovimientoCaja>> movimientos(@PathVariable UUID id){TenantUserDetails u=usuario();return ResponseEntity.ok(caja.resumen(u.getEmpresaId(),id).movimientos());}
 @PostMapping("/{id}/income") public ResponseEntity<MovimientoCaja> ingreso(@PathVariable UUID id,@RequestBody Movimiento r){TenantUserDetails u=usuario();return ResponseEntity.ok(caja.ingreso(u.getEmpresaId(),id,r.monto(),r.metodo(),r.concepto(),r.nota(),r.claveIdempotencia()));}
 @PostMapping("/{id}/expense") public ResponseEntity<MovimientoCaja> egreso(@PathVariable UUID id,@RequestBody Movimiento r){TenantUserDetails u=usuario();return ResponseEntity.ok(caja.egreso(u.getEmpresaId(),id,r.monto(),r.metodo(),r.concepto(),r.nota(),r.claveIdempotencia()));}
 @PostMapping("/{id}/close") public ResponseEntity<SesionCaja> cerrar(@PathVariable UUID id,@RequestBody Cierre r){TenantUserDetails u=usuario();return ResponseEntity.ok(caja.cerrarIdempotente(u.getEmpresaId(),id,r.efectivoContado(),r.nota(),r.motivoDiferencia(),r.claveIdempotencia()));}
 @GetMapping("/history") public ResponseEntity<List<SesionCaja>> historial(@RequestParam(required=false) String buscar,@RequestParam(required=false) UUID sucursalId,@RequestParam(required=false) UUID responsable,@RequestParam(required=false) String estado,@RequestParam(required=false) Boolean conDiferencia){TenantUserDetails u=usuario();return ResponseEntity.ok(caja.historial(u.getEmpresaId(),buscar,sucursalId,responsable,estado,conDiferencia));}
 @GetMapping(value="/{id}/close-report",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<byte[]> reporte(@PathVariable UUID id){TenantUserDetails u=usuario();return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"inline; filename=cierre-caja-"+id+".pdf").body(caja.generarCierre(u.getEmpresaId(),id));}
}
