ALTER TABLE configuracion_empresa_fase2
  ADD COLUMN IF NOT EXISTS unidad_altura VARCHAR(10) NOT NULL DEFAULT 'METROS',
  ADD COLUMN IF NOT EXISTS unidad_peso VARCHAR(10) NOT NULL DEFAULT 'KG',
  ADD COLUMN IF NOT EXISTS unidad_temperatura VARCHAR(2) NOT NULL DEFAULT 'C';
