ALTER TABLE antecedentes_medicos
  ADD COLUMN IF NOT EXISTS fecha_desconocida BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  ADD COLUMN IF NOT EXISTS relacion_familiar VARCHAR(60),
  ADD COLUMN IF NOT EXISTS registrado_por UUID REFERENCES usuarios(id),
  ADD COLUMN IF NOT EXISTS creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
