ALTER TABLE alergias_paciente
  ADD COLUMN IF NOT EXISTS estado VARCHAR(25) NOT NULL DEFAULT 'ACTIVA',
  ADD COLUMN IF NOT EXISTS fecha_aproximada DATE,
  ADD COLUMN IF NOT EXISTS observaciones TEXT,
  ADD COLUMN IF NOT EXISTS registrado_por UUID REFERENCES usuarios(id),
  ADD COLUMN IF NOT EXISTS creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
