ALTER TABLE recetas ADD COLUMN IF NOT EXISTS numero VARCHAR(30), ADD COLUMN IF NOT EXISTS anulado_en TIMESTAMP, ADD COLUMN IF NOT EXISTS anulado_por UUID REFERENCES usuarios(id), ADD COLUMN IF NOT EXISTS motivo_anulacion TEXT, ADD COLUMN IF NOT EXISTS snapshot TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS uk_recetas_numero ON recetas(numero) WHERE numero IS NOT NULL;
