package com.citacloud.app.models;
import jakarta.persistence.*; import java.time.*; import java.util.UUID;
@Entity @Table(name="recetas") public class Receta {
 @Id @GeneratedValue private UUID id; @Column(name="empresa_id",nullable=false) private UUID empresaId; @Column(unique=true) private String numero;
 @Column(name="paciente_id",nullable=false) private UUID pacienteId; @Column(name="diagnostico_id") private UUID diagnosticoId;
 @Column(name="indicaciones_generales",columnDefinition="TEXT") private String indicacionesGenerales; @Column(columnDefinition="TEXT") private String observaciones; @Column(name="vigente_hasta") private LocalDate vigenteHasta;
 private String estado="BORRADOR"; @Column(name="creado_por") private UUID creadoPor; @Column(name="creado_en") private LocalDateTime creadoEn; @Column(name="emitido_en") private LocalDateTime emitidoEn; @Column(name="actualizado_en") private LocalDateTime actualizadoEn;
 @Column(name="anulado_en") private LocalDateTime anuladoEn; @Column(name="anulado_por") private UUID anuladoPor; @Column(name="motivo_anulacion",columnDefinition="TEXT") private String motivoAnulacion; @Column(name="snapshot",columnDefinition="TEXT") private String snapshot;
 public UUID getId(){return id;} public UUID getEmpresaId(){return empresaId;} public String getNumero(){return numero;} public UUID getPacienteId(){return pacienteId;} public UUID getDiagnosticoId(){return diagnosticoId;} public String getIndicacionesGenerales(){return indicacionesGenerales;} public String getObservaciones(){return observaciones;} public LocalDate getVigenteHasta(){return vigenteHasta;} public String getEstado(){return estado;} public UUID getCreadoPor(){return creadoPor;} public LocalDateTime getCreadoEn(){return creadoEn;} public LocalDateTime getEmitidoEn(){return emitidoEn;} public LocalDateTime getActualizadoEn(){return actualizadoEn;} public void setEmpresaId(UUID v){empresaId=v;} public void setNumero(String v){numero=v;} public void setPacienteId(UUID v){pacienteId=v;} public void setDiagnosticoId(UUID v){diagnosticoId=v;} public void setIndicacionesGenerales(String v){indicacionesGenerales=v;} public void setObservaciones(String v){observaciones=v;} public void setVigenteHasta(LocalDate v){vigenteHasta=v;} public void setEstado(String v){estado=v;} public void setCreadoPor(UUID v){creadoPor=v;} public void setCreadoEn(LocalDateTime v){creadoEn=v;} public void setEmitidoEn(LocalDateTime v){emitidoEn=v;} public void setActualizadoEn(LocalDateTime v){actualizadoEn=v;} public void setSnapshot(String v){snapshot=v;} public void anular(UUID u,String motivo){estado="ANULADA";anuladoPor=u;motivoAnulacion=motivo;anuladoEn=LocalDateTime.now();}
}
